{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/vk-sxd0e-002;Reporting_KOMOK",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "vk-sxd0e-002",
            "database": "Reporting_KOMOK"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "vk-sxd0e-002;Reporting_KOMOK",
          "Username": "axel.hjelmervik.hansen@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "År",
            "dataType": "string",
            "sourceColumn": "År"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          },
          {
            "name": "Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364",
            "expression": [
              "",
              "",
              "VAR BruttoDriftsinntekterIAlt = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGD13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(BruttoDriftsinntekterIAlt)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UbrukteLaaneMidlerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"9100\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbrukteLaaneMidlerNyTabell =  ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG92\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(UbrukteLaaneMidlerGammelTabell),",
              "        UbrukteLaaneMidlerNyTabell,",
              "        UbrukteLaaneMidlerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)",
              ""
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Valgt regionkode",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "RETURN(SelectedRegion)"
            ]
          },
          {
            "name": "Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202",
            "expression": [
              "",
              "",
              "",
              "VAR UbundetInvesteringsFondGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"53\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbundetInvesteringsFondNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG69\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UbundetInvesteringsFondGammelTabell),",
              "        UbundetInvesteringsFondNyTabell,",
              "        UbundetInvesteringsFondGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"5970\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG71\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UdekketBelopIInvesteringsregnskapetGammelTabell),",
              "        UdekketBelopIInvesteringsregnskapetNyTabell,",
              "        UdekketBelopIInvesteringsregnskapetGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Netto Driftsresultat - AGD23 - 12364",
            "expression": [
              "",
              "",
              "VAR NettoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGD23\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(NettoDriftsresultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Disposisjonsfond (K) - 56 - 12364",
            "expression": [
              "",
              "",
              "VAR Disposisjonsfond = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"56\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(Disposisjonsfond)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364",
            "expression": [
              "",
              "",
              "VAR AaretsMerforbrukIDriftsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]),[Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGD29\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AaretsMerforbrukIDriftsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364",
            "expression": [
              "",
              "",
              "VAR AvsetningTilBundneFondNetto = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGD74\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = AvsetningTilBundneFondNetto",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Utlån - 22/KG48 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "VAR UtlaanGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"22\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UtlaanNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG48\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    ) ",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UtlaanGammelTabell),",
              "        UtlaanNyTabell,",
              "        UtlaanGammelTabell",
              "    )",
              "",
              "RETURN(",
              "    Resultat",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364",
            "expression": [
              "",
              "",
              "VAR LangsiktigGjeldEkslPensjonsforpliktelser =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"KG32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "RETURN(",
              "    LangsiktigGjeldEkslPensjonsforpliktelser",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Renteeksponert gjeld - KG39 - 12364",
            "expression": [
              "",
              "",
              "VAR RenteeksponertGjeld = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"KG39\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(RenteeksponertGjeld)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177",
            "expression": [
              "",
              "",
              "VAR UdisponertIInvesteringsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"5960\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(UdisponertIInvesteringsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Rammetilskudd - A800 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR RammetilskuddGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A800\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR RammetilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A800\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(RammetilskuddGammelTabell),",
              "        RammetilskuddNyTabell,",
              "        RammetilskuddGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR SkattGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A870\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkattNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD75\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkattGammelTabell),",
              "        SkattNyTabell,",
              "        SkattGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR EiendomsskattTotalGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG10\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR EiendomsskattTotalNyTabelll =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG10\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(EiendomsskattTotalGammelTabell),",
              "        EiendomsskattTotalNyTabelll,",
              "        EiendomsskattTotalGammelTabell",
              "    )",
              "",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR SkatteInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"877\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkatteInntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD76\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkatteInntekterGammelTabell),",
              "        SkatteInntekterNyTabell,",
              "        SkatteInntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Brukerbetalinger - A600 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR BrukerbetalingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A600\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR BrukerbetalingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A600\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(BrukerbetalingerGammelTabell),",
              "        BrukerbetalingerNyTabell,",
              "        BrukerbetalingerGammelTabell",
              "    )",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre statlige overføringer - A810/AGD77 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR OverforingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A810\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD77\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(OverforingerGammelTabell),",
              "        OverforingerNyTabell,",
              "        OverforingerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR LonnOgOppgGodtgjorelserGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG15\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR LonnOgOppgGodtgjorelserNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG15\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(LonnOgOppgGodtgjorelserGammelTabell),",
              "        LonnOgOppgGodtgjorelserNyTabell,",
              "        LonnOgOppgGodtgjorelserGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avskrivninger - A590 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR AvskrivningerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A590\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AvskrivningerNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"A590\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(AvskrivningerGammelTabell),",
              "        AvskrivningerNyTabell,",
              "        AvskrivningerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR SumDriftsinntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD45\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SumDriftsinntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD45\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SumDriftsinntekterGammelTabell),",
              "        SumDriftsinntekterNyTabell,",
              "        SumDriftsinntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG23 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG23\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG23\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG23 - 12320/13552",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG23\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG23\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG24 - 12328/13551",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG24\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG24\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG24 - 12320/13552",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG24\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG24\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG25 - 12328/13551",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG25\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG25\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG25 - 12320/13552",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG25\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG25\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG26 - 12328/13551",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG26\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG26\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG26 - 12320/13552",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG26\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG26\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Custom AGD22/ Original AGD85 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR SumEksterneFinansinntekterDriftsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD30\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SumEksterneFinansutgifterDriftsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD31\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR NettoFinansUtgifterGammelTabell = SumEksterneFinansinntekterDriftsregnskapet - SumEksterneFinansutgifterDriftsregnskapet",
              "",
              "",
              "",
              "VAR NettoFinansUtgifterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD85\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(NettoFinansUtgifterGammelTabell),",
              "        NettoFinansUtgifterNyTabell,",
              "        NettoFinansUtgifterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG28 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG28\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG28\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG29\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG29\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12328",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG30\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(DifferanseGammelTabell)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG31 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG31\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG31\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG32 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG33 - 12328",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG33\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(DifferanseGammelTabell)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12320/13552",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG29\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG29\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12320/13552",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG30\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG30\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Befolkning",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(LEFT(SELECTEDVALUE('År'[År]), 4))",
              "",
              "VAR EtAarSiden = FORMAT(ValgtAar, \"####K4\")",
              "",
              "VAR Resultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"01222\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Befolkning ved utgangen av kvartalet\"),",
              "        FILTER(ALL('År'[År]), [År] = EtAarSiden)",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364",
            "expression": [
              "",
              "",
              "VAR AGI1 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGI1\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AGI1)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Sosiale utgifter - AG35 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR AG35 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG35\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AG35)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Dekning av tidligere års merforbruk og udekket beløp (K) - 530/AD530 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DekningGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"530\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DekningNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AD530\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DekningGammelTabell),",
              "        DekningNyTabell,",
              "        DekningGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ]
          },
          {
            "name": "Deflator",
            "description": "Grunntall",
            "expression": [
              "",
              "",
              "VAR Deflator = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"DLO01\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Deflator\")",
              "    )",
              "",
              "RETURN(Deflator)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Lønnsvekst",
            "description": "Grunntall",
            "expression": [
              "",
              "",
              "VAR Lonnsvekst = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"DLO01\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Lønnsvekst\")",
              "    )",
              "",
              "RETURN(Lonnsvekst)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG27/AGD84 - 12328/13551",
            "expression": [
              "",
              "",
              "VAR DiffKonsernGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG27\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Utlaan = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelTabell = DiffKonsernGammelTabell",
              "",
              "VAR DiffKonsernNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD84\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DiffKonsernGammelTabell),",
              "        DiffKonsernNyTabell,",
              "        GammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Artnavn",
            "dataType": "string",
            "sourceColumn": "Artnavn"
          },
          {
            "name": "ArtkodeNavn",
            "dataType": "string",
            "sourceColumn": "ArtkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Art = Source{[Schema=\"dbo\",Item=\"Art\"]}[Data]",
                "in",
                "    dbo_Art"
              ]
            }
          }
        ]
      },
      {
        "name": "Balansedata",
        "columns": [
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Balansedatanavn",
            "dataType": "string",
            "sourceColumn": "Balansedatanavn"
          },
          {
            "name": "BalansedatakodeNavn",
            "dataType": "string",
            "sourceColumn": "BalansedatakodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Balansedata = Source{[Schema=\"dbo\",Item=\"Balansedata\"]}[Data]",
                "in",
                "    dbo_Balansedata"
              ]
            }
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Funksjonnavn",
            "dataType": "string",
            "sourceColumn": "Funksjonnavn"
          },
          {
            "name": "FunksjonkodeNavn",
            "dataType": "string",
            "sourceColumn": "FunksjonkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Funksjon = Source{[Schema=\"dbo\",Item=\"Funksjon\"]}[Data]",
                "in",
                "    dbo_Funksjon"
              ]
            }
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Regnskapsbegrep",
        "columns": [
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Regnskapsbegrepnavn",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepnavn"
          },
          {
            "name": "RegnskapsbegrepkodeNavn",
            "dataType": "string",
            "sourceColumn": "RegnskapsbegrepkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Regnskapsbegrep = Source{[Schema=\"dbo\",Item=\"Regnskapsbegrep\"]}[Data]",
                "in",
                "    dbo_Regnskapsbegrep"
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Kilde",
            "dataType": "string",
            "sourceColumn": "Kilde"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Variabelkode",
            "dataType": "string",
            "sourceColumn": "Variabelkode"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "KOMØK Indikatorer",
        "columns": [
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Hovedtall",
            "dataType": "int64",
            "sourceColumn": "Hovedtall"
          },
          {
            "name": "Tjenesteområder",
            "dataType": "int64",
            "sourceColumn": "Tjenesteområder"
          },
          {
            "name": "Øko- Oversikt",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt"
          },
          {
            "name": "Øko- Oversikt ekskl foretak",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt ekskl foretak"
          },
          {
            "name": "Indeksert",
            "dataType": "string",
            "sourceColumn": "Indeksert"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_KOMØK Indikatorer\" = Source{[Schema=\"dbo\",Item=\"KOMØK Indikatorer\"]}[Data]",
                "in",
                "    #\"dbo_KOMØK Indikatorer\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "+Netto driftsresultat (pst)",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        [Grunntall - Netto Driftsresultat - AGD23 - 12364], ",
              "        [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "    ) * 100",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            Resultat, 1",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Disposisjonsfond korrigert for årets netto merforbuk i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Disposisjonsfond (K) - 56 - 12364]) || ",
              "                ISBLANK([Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364])",
              "",
              "VAR DIM56 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"56\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG65 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG65\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD32 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD89 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD89\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD93 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD93\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD94 = AGD89 - AGD93",
              "",
              "VAR GammelResultat =",
              "    DIVIDE(",
              "        (DIM56 + AGD32) * 100,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR NyResultat =",
              "    DIVIDE(",
              "        (KG65 + AGD94) * 100, ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        GammelResultat,",
              "        NyResultat",
              "    )",
              "",
              "RETURN (",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Korrigert netto driftsresultat i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364])",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364] ",
              "                    + [Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 1",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke =",
              "    ISBLANK([Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt]) ||",
              "    ISBLANK([Grunntall - Utlån - 22/KG48 - 12177/13202]) ||",
              "    ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) ||",
              "    ISBLANK([Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202])",
              "",
              "var formel =",
              "    DIVIDE(",
              "        ([Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt] - ",
              "            [Grunntall - Utlån - 22/KG48 - 12177/13202] - ",
              "            [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202]) * 100, ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "    ",
              "RETURN(",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(formel , 1)",
              "    )  ",
              ")"
            ]
          },
          {
            "name": "Renteeksponert lånegjeld i prosent av langsiktig lånegjeld",
            "expression": [
              "",
              "",
              "",
              "VAR HarBlanke = ISBLANK([Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt]) || ",
              "                ISBLANK([Grunntall - Renteeksponert gjeld - KG39 - 12364])",
              "",
              "VAR KG39 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12135\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"KG39\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "",
              "RETURN(",
              "    ROUND(",
              "        DIVIDE(KG39 * 100, [Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt]), 1",
              "    )",
              ")",
              ""
            ]
          },
          {
            "name": "Korrigert netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR Pre2020 = ",
              "        DIVIDE(",
              "            [Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt]",
              "                - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "                - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "                - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]",
              "                - ([Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202] ",
              "                - [Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177]), ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        )",
              "",
              "VAR Post2020 = ",
              "        DIVIDE(",
              "            [Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt]",
              "                - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "                - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "                - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]",
              "                - [Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202], ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020,",
              "        Post2020",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat * 100, 1)",
              ")"
            ]
          },
          {
            "name": "Skatt",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551]) ||",
              "                ISBLANK([Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]) ||",
              "                ISBLANK([Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551])",
              "",
              "VAR SkattSum = [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551] ",
              "               + [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]",
              "               + [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551]",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(SkattSum, 3)",
              "    )",
              ")"
            ]
          },
          {
            "name": "Andre Inntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AndreInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre salgs- og leieinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingsInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringsinntekter med krav til motytelse i drift\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AndreOverforingerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre overføringer\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerOgTilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringer og tilskudd fra andre\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SalgsLeieinntekterDriftNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Salgs- og leieinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brukerbetalinger - A600 - 12328/13551]) ||",
              "                ISBLANK(AndreInntekterGammelTabell) ||",
              "                ISBLANK(OverforingsInntekterGammelTabell) ||",
              "                ISBLANK(AndreOverforingerGammelTabell) ||",
              "                ISBLANK(OverforingerOgTilskuddNyTabell) ||",
              "                ISBLANK(SalgsLeieinntekterDriftNyTabell) ",
              "",
              "VAR Pre2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13551]",
              "                        + AndreInntekterGammelTabell",
              "                        + AndreOverforingerGammelTabell",
              "                        + OverforingsInntekterGammelTabell",
              "",
              "VAR Post2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13551]",
              "                        + OverforingerOgTilskuddNyTabell",
              "                        + SalgsLeieinntekterDriftNyTabell",
              "",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020Resultat,",
              "        Post2020Resultat",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 3)",
              ")"
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551]",
              "                + [Skatt]                ",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Deflatert",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR DeflatertProsentToAarSiden = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"DLO01\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Deflator\"),",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR DeflatertProsentEtAarSiden = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"DLO01\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Deflator\"),",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR DeflatertToAarSiden = 1.0 + DIVIDE(DeflatertProsentToAarSiden, 100)",
              "VAR DeflatertEtAarSiden = 1.0 + DIVIDE(DeflatertProsentEtAarSiden, 100)",
              "",
              "VAR DeflatertVekstEtAarSiden = DeflatertToAarSiden * DeflatertEtAarSiden",
              "",
              "",
              "VAR FrieInntekter = ",
              "    CALCULATE([Nominell vekst i frie inntekter],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR DeflatertVerdi2017 = FrieInntekter",
              "VAR DeflatertVerdi2018 = DIVIDE(FrieInntekter, DeflatertToAarSiden)",
              "VAR DeflatertVerdi2019 = DIVIDE(FrieInntekter, DeflatertVekstEtAarSiden)",
              "    ",
              "VAR Resultat =",
              "    IF(ValgtAar = 2018,",
              "        FrieInntekter,",
              "        IF(ValgtAar = 2019,",
              "            DeflatertVerdi2018,",
              "            IF(ValgtAar = 2020,",
              "                DeflatertVerdi2019",
              "            )",
              "        )",
              "    )",
              "",
              "RETURN(Resultat)"
            ]
          },
          {
            "name": "Brutto driftsresultat (før avskrivninger) i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "",
              "/*VAR BruttoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brutto driftsresultat (D=A-B-C)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "*/",
              "",
              "VAR BruttoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brutto driftsresultat (D=A-B-C)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        (BruttoDriftsresultat + [Grunntall - Avskrivninger - A590 - 12328/13551]) * 100,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto finanstransaksjoner i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "var valgte_aar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "var konsern =",
              "[Grunntall - AG28 - 12328/13551] + [Grunntall - AG29 - 12328/13551] + [Grunntall - AG31 - 12328/13551]",
              "    + [Grunntall - AG32 - 12328/13551]",
              "",
              "VAR pre2020 = ",
              "    DIVIDE(",
              "        -([Grunntall - Custom AGD22/ Original AGD85 - 12328/13551] - konsern) * 100,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "var post2020 = ",
              "    DIVIDE(",
              "        -(-[Grunntall - Custom AGD22/ Original AGD85 - 12328/13551] - konsern) * 100,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "var resultat =",
              "IF(valgte_aar < 2020, pre2020, post2020)",
              "",
              "RETURN(",
              "    ROUND(resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Handlingsrom (justert netto driftsresultat) (pst)",
            "expression": [
              "",
              "",
              "var resultat = ",
              "DIVIDE([Handlingsrom (justert netto driftsresultat)] * 1000, ",
              "    [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]",
              ") * 100",
              "",
              "RETURN(",
              "    ROUND(resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Investeringsutgifter i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumInvesteringsUtgifter = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AGI20\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG19 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG19\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG20 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG20\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG21 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG21\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG22 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG22\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG28 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG28\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI39 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI39\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI40 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI40\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR InvesteringsutgifterEksAvdrag = AGI39 + AGI40",
              "",
              "VAR ResultatNy = ",
              "    DIVIDE((InvesteringsutgifterEksAvdrag + AG19 + AG20 + AG21 + AG22 + AG28) * 100,",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]",
              "            - [Grunntall - AG23 - 12320/13552]",
              "            - [Grunntall - AG24 - 12320/13552]",
              "            - [Grunntall - AG25 - 12320/13552]",
              "            - [Grunntall - AG26 - 12320/13552])",
              "",
              "",
              "",
              "VAR ResultatGammel = ",
              "    DIVIDE((SumInvesteringsUtgifter + AG19 + AG20 + AG21 + AG22 + AG28) * 100,",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]",
              "            - [Grunntall - AG23 - 12320/13552]",
              "            - [Grunntall - AG24 - 12320/13552]",
              "            - [Grunntall - AG25 - 12320/13552]",
              "            - [Grunntall - AG26 - 12320/13552])",
              "",
              "VAR Resultat =",
              "    IF(ValgtAar < 2020,",
              "        ResultatGammel,",
              "        ResultatNy",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto bruk av lån i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR DIM929 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"929\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM529 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"529\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI41 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI41\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI42 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI42\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI46 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI46\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG5 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI17 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI17\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI48 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13552\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI48\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG32 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG33 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13552\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG33\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Pre2020 = ",
              "    DIVIDE(-((DIM529 - DIM929) + (AG6 - AG13) + AG5 - AGI17 ",
              "            + ([Grunntall - AG29 - 12320/13552] + [Grunntall - AG30 - 12320/13552]) + (AG32 + AG33)) * 100,",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]",
              "            - ([Grunntall - AG23 - 12320/13552]",
              "                + [Grunntall - AG24 - 12320/13552]",
              "                + [Grunntall - AG25 - 12320/13552]",
              "                + [Grunntall - AG26 - 12320/13552]))",
              "",
              "var AGI41min929 =",
              "    AGI41 - DIM929",
              "",
              "var AGI42minAGI46 =",
              "    AGI42 - AGI46",
              "",
              "var AG32plusAG33 =",
              "    AG32 + AG33",
              "",
              "var AG29plusAG30 =",
              "    [Grunntall - AG29 - 12320/13552] + [Grunntall - AG30 - 12320/13552]",
              "",
              "",
              "VAR Post2020 =",
              "    DIVIDE(",
              "        -(AGI41min929 + AGI42minAGI46 + AG5 - AGI17 + AGI48 ",
              "            + AG29plusAG30 +  AG32plusAG33) * 100,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020,",
              "        Post2020",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "-Avskrivninger minus avdrag",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "var netto_avdrag =",
              "    -(AG6 - AG13) - AG5 - [Grunntall - AG29 - 12328/13551] - [Grunntall - AG32 - 12328/13551]",
              "",
              "/* AG6 and AG13 is only valid pre-2020, but should always have values */",
              "var blank_check_pre2020 =",
              "    ISBLANK(AG6) || ISBLANK(AG13)",
              "",
              "var blank_check = ",
              "    ISBLANK(AG5) || ISBLANK([Grunntall - AG29 - 12328/13551]) ||",
              "    ISBLANK([Grunntall - AG32 - 12328/13551])",
              "",
              "var formel = ",
              "    -(netto_avdrag + [Grunntall - Avskrivninger - A590 - 12328/13551])",
              "",
              "var resultat =",
              "    if (ValgtAar < 2020,",
              "        /* if either of the blank checks is true a value is missing and we should return blank */ ",
              "        if (blank_check_pre2020 || blank_check, BLANK(), formel),",
              "        if (blank_check, blank(), formel)",
              "    )",
              "",
              "",
              "RETURN(ROUND(DIVIDE(resultat, 1000), 1))"
            ]
          },
          {
            "name": "Netto Drift i pst",
            "expression": [
              "",
              "",
              "VAR prosentResultat = DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364], [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100",
              "",
              "RETURN(ROUND(prosentResultat, 1))"
            ]
          },
          {
            "name": "-Netto avsetning til bundne driftsfond (pst)",
            "expression": [
              "",
              "",
              "VAR prosentResultat = DIVIDE([Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364], ",
              "                                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100",
              "",
              "RETURN(ROUND(prosentResultat, 1))"
            ]
          },
          {
            "name": "-Avskrivninger minus avdrag (pst)",
            "expression": [
              "",
              "",
              "VAR prosentResulat = ",
              "    DIVIDE([-Avskrivninger minus avdrag] * 1000, ",
              "        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]",
              "    ) * 100",
              "",
              "RETURN(ROUND(prosentResulat, 1))"
            ]
          },
          {
            "name": "Handlingsrom (justert netto driftsresultat)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AGD66orAGD89 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AGD66\", \"AGD89\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM550 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"550\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM950 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"950\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM530orAD530 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"530\", \"AD530\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DelEn = ",
              "    AGD66orAGD89",
              "    - (DIM550 - DIM950)",
              "    - DIM530orAD530",
              "",
              "VAR DelTo = [Avskrivninger minus avdrag (1000 kr)] ",
              "            + [Grunntall - AG29 - 12328/13551] + [Grunntall - AG30 - 12328] ",
              "            + [Grunntall - AG32 - 12328/13551] + [Grunntall - AG33 - 12328]",
              "   ",
              "",
              "VAR Resultat = DelEn + DelTo",
              "",
              "RETURN(",
              "    ROUND(DIVIDE(Resultat, 1000), 1)",
              ")"
            ]
          },
          {
            "name": "Renteinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG36 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG36\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD79 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD79\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AD905 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AD905\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(",
              "            (AG36 - AD905 - [Grunntall - AG31 - 12328/13551]) * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        ),",
              "        DIVIDE(",
              "            (AGD79 - [Grunntall - AG31 - 12328/13551]) * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        )",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")",
              "",
              ""
            ]
          },
          {
            "name": "+Utbytte",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AD905 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AD905\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(",
              "            AD905 * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        ),",
              "        DIVIDE(",
              "            AD905 * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        )",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "+Netto gevinst (+) fin. omløpsm.",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR DIM909 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"909\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM509 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"509\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD83 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD83\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE((DIM909 - DIM509) * 100, [Korrigerte driftsinntekter - 12328/13551]),",
              "        DIVIDE(AGD83 * 100, [Korrigerte driftsinntekter - 12328/13551])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "-Renteutgifter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG42 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG42\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM509 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"509\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD82 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD82\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(",
              "            -(AG42 + [Grunntall - AG28 - 12328/13551]) * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        ),",
              "        DIVIDE(",
              "            -(AGD82 + [Grunntall - AG28 - 12328/13551]) * 100, ",
              "            [Korrigerte driftsinntekter - 12328/13551]",
              "        )",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "-Netto avdrag",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG5 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "        CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelResultat = ",
              "    DIVIDE(",
              "        -(AG5 + AG6 + [Grunntall - AG29 - 12328/13551] - [Grunntall - AG32 - 12328/13551]), ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR NyResultat = ",
              "    DIVIDE(",
              "        -(AG5 + [Grunntall - AG29 - 12328/13551] - [Grunntall - AG32 - 12328/13551]), ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        GammelResultat * 100,",
              "        NyResultat * 100",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto finans",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "var pre2020 = ",
              "    DIVIDE(",
              "        ([Grunntall - Custom AGD22/ Original AGD85 - 12328/13551] - [Grunntall - AG27/AGD84 - 12328/13551]) * 100, ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR post2020 = ",
              "    DIVIDE(",
              "        (-[Grunntall - Custom AGD22/ Original AGD85 - 12328/13551] - [Grunntall - AG27/AGD84 - 12328/13551]) * 100, ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "var resultat = ",
              "    IF(ValgtAar < 2020, pre2020, post2020)",
              "",
              "",
              "RETURN(",
              "    ROUND(",
              "        resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Grunnskole",
            "expression": [
              "",
              "",
              "VAR FGK8b = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK8b\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK8b * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), ",
              "                                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 2",
              "    )",
              ")"
            ]
          },
          {
            "name": "VAR",
            "expression": [
              "",
              "",
              "VAR FGK14 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK14\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK14 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Helse/omsorg",
            "expression": [
              "",
              "",
              "VAR FGK9 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK9\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = ",
              "    DIVIDE(",
              "        FGK9 * 100, ",
              "        [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364]",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        DIVIDE(",
              "            ProsentResultat, ",
              "            100",
              "        ) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), ",
              "        [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Samferdsel",
            "expression": [
              "",
              "",
              "VAR FGK5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK5 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Bolig",
            "expression": [
              "",
              "",
              "VAR FGK16 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK16\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK16 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), ",
              "                                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Barnehage",
            "expression": [
              "",
              "",
              "VAR FGK7 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK7\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = ",
              "    DIVIDE(",
              "        FGK7 * 100,",
              "        [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364]",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        DIVIDE(",
              "            ProsentResultat,",
              "            100",
              "        ) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100),",
              "        [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Kultur",
            "expression": [
              "",
              "",
              "VAR FGK2 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK2\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK2 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), ",
              "                                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Administrasjon",
            "expression": [
              "",
              "",
              "VAR FGK1b = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK1b\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = ",
              "    DIVIDE(",
              "        FGK1b * 100, ",
              "        [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364]",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        DIVIDE(",
              "            ProsentResultat, ",
              "            100",
              "        ) * [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100, ",
              "        [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Næring",
            "expression": [
              "",
              "",
              "VAR FGK4 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK4\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ProsentResultat = DIVIDE(FGK4 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "VAR Resultat = DIVIDE(DIVIDE(ProsentResultat, 100) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Annet",
            "expression": [
              "",
              "",
              "VAR DIM190 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"190\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM285 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"285\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM290 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"290\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK12 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK12\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK13 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK15 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK15\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK17 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK17\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK1c = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK1c\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK3 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK3\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Korr = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12163\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] IN {\"FGF1b\", \"FGF3\", \"FGF4\", \"FGF7\", \"FGF8\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DimResultat = DIM190 + DIM285 + DIM290 + FGK12 + FGK15 + FGK17 + FGK1c + FGK3 + Korr",
              "",
              "VAR ProsentResultat = ",
              "    DIVIDE(",
              "        DimResultat * 100, ",
              "        [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364]",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        DIVIDE(",
              "            ProsentResultat,",
              "            100",
              "        ) * ([Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364] * 100), ",
              "        [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter (Prosentvis vekst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551]",
              "                + [Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )    ",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551]",
              "                + [Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 0, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((SumEtAarSiden - SumToAarSiden) * 100, SumToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))",
              ""
            ]
          },
          {
            "name": "Skatt i alt (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((SumEtAarSiden - SumToAarSiden) * 100, SumToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Inntekts- og formueskatt (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR A870ogAGD75EtAarSiden = ",
              "    CALCULATE([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR A870ogAGD75ToAarSiden = ",
              "    CALCULATE([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((A870ogAGD75EtAarSiden - A870ogAGD75ToAarSiden) * 100, A870ogAGD75ToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Eiendomsskatt (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG10EtAarSiden = ",
              "    CALCULATE([Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR AG10ToAarSiden = ",
              "    CALCULATE([Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((AG10EtAarSiden - AG10ToAarSiden) * 100, AG10ToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Rammetilskudd (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR A800EtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR A800ToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((A800EtAarSiden - A800ToAarSiden) * 100, A800ToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Andre skatteinntekter (prosentvis vekst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG76og877EtAarSiden = ",
              "    CALCULATE(",
              "        [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR AG76og877ToAarSiden = ",
              "    CALCULATE(",
              "        [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        (AG76og877EtAarSiden - AG76og877ToAarSiden) * 100,",
              "        AG76og877ToAarSiden",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Lønnsutgifter",
            "expression": [
              "",
              "",
              "VAR AG15 = [Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551]",
              "    ",
              "",
              "RETURN(ROUND(DIVIDE(AG15, 1000), 0))"
            ]
          },
          {
            "name": "Lønnsutgifter (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG15EtAarSiden = ",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR AG15ToAarSiden = ",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((AG15EtAarSiden - AG15ToAarSiden) * 100, AG15ToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Sosiale utgifter",
            "expression": [
              "",
              "",
              "VAR Resultat = [Grunntall - Sosiale utgifter - AG35 - 12328/13551]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 0))"
            ]
          },
          {
            "name": "Sosiale utgifter (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG35EtAarSiden = ",
              "    CALCULATE([Grunntall - Sosiale utgifter - AG35 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR AG35ToAarSiden = ",
              "    CALCULATE([Grunntall - Sosiale utgifter - AG35 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((AG35EtAarSiden - AG35ToAarSiden) * 100, AG35ToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Sum lønn inkl. sosiale utgifter",
            "expression": [
              "",
              "",
              "VAR Resultat = [Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551]",
              "                        + [Grunntall - Sosiale utgifter - AG35 - 12328/13551]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 0))"
            ]
          },
          {
            "name": "Sum lønn inkl. sosiale utgifter (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551]",
              "                + [Grunntall - Sosiale utgifter - AG35 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13551]",
              "                + [Grunntall - Sosiale utgifter - AG35 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((SumEtAarSiden - SumToAarSiden) * 100, SumToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "+Netto driftsresultat",
            "expression": [
              "",
              "",
              "ROUND(",
              "    DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364], 1000), ",
              "    1",
              ")"
            ]
          },
          {
            "name": "Rammetilskudd",
            "expression": [
              "",
              "",
              "VAR Resultat = [Grunntall - Rammetilskudd - A800 - 12328/13551]",
              "",
              "RETURN(ROUND(Resultat, 0))"
            ]
          },
          {
            "name": "Andre statlige overføringer",
            "expression": [
              "",
              "",
              "ROUND([Grunntall - Andre statlige overføringer - A810/AGD77 - 12328/13551], 0)"
            ]
          },
          {
            "name": "Dekning tidligere års merforbruk (1000 kr)",
            "expression": [
              "",
              "",
              "VAR Resultat = -[Grunntall - Dekning av tidligere års merforbruk og udekket beløp (K) - 530/AD530 - 12328/13551]",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "-Dekning tidligere års merforbruk (pst)",
            "expression": [
              "",
              "",
              "VAR Resultat = DIVIDE(-[Grunntall - Dekning av tidligere års merforbruk og udekket beløp (K) - 530/AD530 - 12328/13551] * 100,",
              "                        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551])",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Skatt i alt",
            "expression": [
              "",
              "",
              "VAR Resultat = [Skatt]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 0))"
            ]
          },
          {
            "name": "Rammetilskudd.",
            "expression": [
              "",
              "",
              "VAR Resultat = [Rammetilskudd]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 0))"
            ]
          },
          {
            "name": "Eiendomskatt",
            "expression": [
              "",
              "",
              "VAR Resultat = [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 0))"
            ]
          },
          {
            "name": "Befolkningsvekst",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR ForsteAar = CALCULATE([Befolkning],",
              "                    FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "                )",
              "",
              "VAR AndreAar = CALCULATE([Befolkning],",
              "                    FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "                )",
              "",
              "VAR Resultat = DIVIDE(ForsteAar - AndreAar, AndreAar) * 100",
              "",
              "RETURN(Resultat)"
            ]
          },
          {
            "name": "Frie inntekter i alt (pst)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR FrieInntekter = [Grunntall - Rammetilskudd - A800 - 12328/13551] ",
              "               + [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551]",
              "               + [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]",
              "               + [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551]",
              "",
              "VAR FrieInntekterEtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551] +",
              "                [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551]+",
              "                [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]+",
              "                [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR FrieInntekterToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13551] +",
              "                [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551]+",
              "                [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]+",
              "                [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((FrieInntekterEtAarSiden - FrieInntekterToAarSiden) * 100, FrieInntekterToAarSiden)",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Frie inntekter i alt",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        [Grunntall - Rammetilskudd - A800 - 12328/13551] ",
              "            + [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551]",
              "            + [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13551]",
              "            + [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13551], ",
              "        1000",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 0))"
            ]
          },
          {
            "name": "Netto driftsresultat etter bundne fond i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR NettoDriftsResultatGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD66\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR NettoDriftsResultatNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD89\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM550 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"550\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM950 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"950\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD91 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13551\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD91\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR ResultatGammelTabell = ",
              "    DIVIDE(",
              "        NettoDriftsResultatGammelTabell - (DIM550 - DIM950),",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR ResultatNyTabell = ",
              "    DIVIDE(",
              "        NettoDriftsResultatNyTabell - AGD91,",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        ResultatGammelTabell,",
              "        ResultatNyTabell",
              "    )",
              "",
              "RETURN (ROUND(Resultat * 100, 1))"
            ]
          },
          {
            "name": "Avskrivninger",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        -[Grunntall - Avskrivninger - A590 - 12328/13551], ",
              "        [Korrigerte driftsinntekter - 12328/13551]",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat * 100, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Langsiktig gjeld ekskl. pensjonsforpliktelser - manuelt",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR DIM41 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"41\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM42 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"42\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM43 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"43\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM45 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"45\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM46 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"46\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG78 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG78\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG79 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG79\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG80 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG80\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG81 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG81\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR KG113 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Original dimensjonskode]), [Original dimensjonskode] = \"KG113\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelResultat = DIM41 + DIM42 + DIM43 + DIM45 + DIM46",
              "",
              "VAR NyResultat = KG78 + KG79 + KG80 + KG81 + KG113",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        GammelResultat,",
              "        NyResultat",
              "    )",
              "",
              "RETURN(Resultat)",
              "",
              "",
              "",
              ""
            ]
          },
          {
            "name": "Avskrivninger minus avdrag (1000 kr)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AD990orAGD87 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13551\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AD990\", \"AGD87\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelResultat =",
              "    AG5 - [Grunntall - Avskrivninger - A590 - 12328/13551] + (AG6 - AG13) ",
              "",
              "VAR NyResultat =",
              "    AG5 - [Grunntall - Avskrivninger - A590 - 12328/13551]",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        GammelResultat,",
              "        NyResultat",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 0))"
            ]
          },
          {
            "name": "-Netto avsetning til bundne driftsfond",
            "expression": [
              "",
              "",
              "VAR Resultat = [Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 1))"
            ]
          },
          {
            "name": "-Dekning av tidligere års merforbruk",
            "expression": [
              "",
              "",
              "VAR Resultat = -[Grunntall - Dekning av tidligere års merforbruk og udekket beløp (K) - 530/AD530 - 12328/13551]",
              "",
              "RETURN(ROUND(DIVIDE(Resultat, 1000), 1))"
            ]
          },
          {
            "name": "Inntekts- og formueskatt",
            "expression": [
              "",
              "",
              "VAR Resultat = DIVIDE([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13551], 1000)",
              "",
              "RETURN(ROUND(Resultat, 0))"
            ]
          },
          {
            "name": "Korrigerte driftsinntekter - 12328/13551",
            "expression": [
              "",
              "",
              "var valgte_aar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "var blank_check_pre2020 =",
              "    ISBLANK([Grunntall - AG24 - 12328/13551]) || ISBLANK([Grunntall - AG26 - 12328/13551])",
              "",
              "var blank_check =",
              "    ISBLANK([Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551]) ||",
              "    ISBLANK([Grunntall - AG23 - 12328/13551]) || ISBLANK([Grunntall - AG25 - 12328/13551])",
              "",
              "var formel_pre2020 =",
              "    [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551] -",
              "    [Grunntall - AG23 - 12328/13551] - ",
              "    [Grunntall - AG24 - 12328/13551] - ",
              "    [Grunntall - AG25 - 12328/13551] -",
              "    [Grunntall - AG26 - 12328/13551]",
              "",
              "/* AG24 and 26 dont exist from 2020 and are therefore taken out of the formula */",
              "var formel = ",
              "    [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13551] -",
              "    [Grunntall - AG23 - 12328/13551] - ",
              "    [Grunntall - AG25 - 12328/13551]",
              "    ",
              "",
              "",
              "return (",
              "    if (valgte_aar < 2020,",
              "        /* if one or more values are blank, return blank else return the result */",
              "        if (blank_check_pre2020 || blank_check, blank(), formel_pre2020),",
              "        if (blank_check, blank(), formel)",
              "    )",
              ")"
            ]
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "string",
            "sourceColumn": "År"
          },
          {
            "name": "Årstall",
            "dataType": "string",
            "sourceColumn": "Årstall"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4b50dd00-2bc4-4226-adcc-afaa2264d904",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Artkode"
      },
      {
        "name": "ae3dd9e0-6391-4873-814f-f546be9d43af",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "a6a9ef68-bc24-4753-97f0-be9763912084",
        "fromTable": "Alle Data",
        "fromColumn": "Regnskapsbegrepkode",
        "toTable": "Regnskapsbegrep",
        "toColumn": "Regnskapsbegrepkode"
      },
      {
        "name": "d4c5cb7e-0dac-44d5-a7c7-dedcbeec0f20",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "39c4585f-88df-4c90-ba29-7001f983e9ba",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabelkode"
      },
      {
        "name": "bd66c095-a64b-4453-952a-4fe6eb88af22",
        "fromTable": "Alle Data",
        "fromColumn": "Balansedatakode",
        "toTable": "Balansedata",
        "toColumn": "Balansedatakode"
      },
      {
        "name": "06c4c976-b83f-42c4-90bf-3bd377e09189",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Funksjonkode"
      },
      {
        "name": "174104c3-8d7d-42f6-91f0-91c9e1a69e8a",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      }
    ],
    "roles": [
      {
        "name": "Brukere",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "I04\\VK.DB.VK-SXD0E-002_KOMOK.DBO",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1078585"
          }
        ]
      },
      {
        "name": "PowerBI",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "I04\\vk-PowerBIService",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1042837"
          }
        ]
      },
      {
        "name": "API",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}