{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/vk-sxd0e-002;Reporting_KOMOK",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "vk-sxd0e-002",
            "database": "Reporting_KOMOK"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "vk-sxd0e-002;Reporting_KOMOK",
          "Username": "hama.keli@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Kildekode",
            "dataType": "string",
            "sourceColumn": "Kildekode"
          },
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "År",
            "dataType": "string",
            "sourceColumn": "År"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi"
          },
          {
            "type": "calculated",
            "name": "Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "",
              ""
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          },
          {
            "name": "Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364",
            "expression": [
              "",
              "",
              "VAR BruttoDriftsinntekterIAlt = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Brutto driftsinntekter i alt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(BruttoDriftsinntekterIAlt)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UbrukteLaaneMidlerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Memoriakonto for ubrukte lånemidler (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbrukteLaaneMidlerNyTabell =  ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"F.1.1 Ubrukte lånemidler\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(UbrukteLaaneMidlerGammelTabell),",
              "        UbrukteLaaneMidlerNyTabell,",
              "        UbrukteLaaneMidlerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)",
              ""
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Valgt regionkode",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "RETURN(SelectedRegion)"
            ]
          },
          {
            "name": "Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202",
            "expression": [
              "",
              "",
              "",
              "VAR UbundetInvesteringsFondGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Ubundne investeringsfond (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbundetInvesteringsFondNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"C.2.1 Ubundet investeringsfond\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UbundetInvesteringsFondGammelTabell),",
              "        UbundetInvesteringsFondNyTabell,",
              "        UbundetInvesteringsFondGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Udekket beløp i investeringsregnskapet (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"C.2.3 Udekket beløp i investeringsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UdekketBelopIInvesteringsregnskapetGammelTabell),",
              "        UdekketBelopIInvesteringsregnskapetNyTabell,",
              "        UdekketBelopIInvesteringsregnskapetGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Netto Driftsresultat - AGD23 - 12364",
            "expression": [
              "",
              "",
              "VAR NettoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Netto driftsresultat\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(NettoDriftsresultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Disposisjonsfond (K) - 56 - 12364",
            "expression": [
              "",
              "",
              "VAR Disposisjonsfond = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Disposisjonsfond (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(Disposisjonsfond)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364",
            "expression": [
              "",
              "",
              "VAR AaretsMerforbrukIDriftsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]),[Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Årets merforbruk i driftsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AaretsMerforbrukIDriftsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364",
            "expression": [
              "",
              "",
              "VAR AvsetningTilBundneFondNetto = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Avsetning til bundne fond (netto)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = AvsetningTilBundneFondNetto",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Utlån - 22/KG48 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "VAR UtlaanGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Utlån (anleggsmidler)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UtlaanNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"A.2.3 Utlån\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    ) ",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UtlaanGammelTabell),",
              "        UtlaanNyTabell,",
              "        UtlaanGammelTabell",
              "    )",
              "",
              "RETURN(",
              "    Resultat",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364",
            "expression": [
              "",
              "",
              "VAR LangsiktigGjeldEkslPensjonsforpliktelser =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Langsiktig gjeld ekskl. pensjonsforpliktelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "RETURN(",
              "    LangsiktigGjeldEkslPensjonsforpliktelser",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Renteeksponert gjeld - KG39 - 12364",
            "expression": [
              "",
              "",
              "VAR RenteeksponertGjeld = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Renteeksponert gjeld\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(RenteeksponertGjeld)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177",
            "expression": [
              "",
              "",
              "VAR UdisponertIInvesteringsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Udisponert i investeringsregnskapet (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(UdisponertIInvesteringsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Rammetilskudd - A800 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR RammetilskuddGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]),  [Artnavn] = \"Rammetilskudd\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR RammetilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]),  [Artnavn] = \"Rammetilskudd\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(RammetilskuddGammelTabell),",
              "        RammetilskuddNyTabell,",
              "        RammetilskuddGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR SkattGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Skatt på inntekt og formue\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkattNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Inntekts- og formueskatt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkattGammelTabell),",
              "        SkattNyTabell,",
              "        SkattGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR EiendomsskattTotalGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Eiendomsskatt totalt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR EiendomsskattTotalNyTabelll =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Eiendomsskatt totalt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(EiendomsskattTotalGammelTabell),",
              "        EiendomsskattTotalNyTabelll,",
              "        EiendomsskattTotalGammelTabell",
              "    )",
              "",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2",
            "expression": [
              "",
              "",
              "VAR SkatteInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre direkte og indirekte skatter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkatteInntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre skatteinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkatteInntekterGammelTabell),",
              "        SkatteInntekterNyTabell,",
              "        SkatteInntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Brukerbetalinger - A600 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR BrukerbetalingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brukerbetalinger\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR BrukerbetalingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brukerbetalinger\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(BrukerbetalingerGammelTabell),",
              "        BrukerbetalingerNyTabell,",
              "        BrukerbetalingerGammelTabell",
              "    )",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre statlige overføringer - A810/AGD77 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR OverforingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre statlige overføringer\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre overføringer og tilskudd fra staten\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(OverforingerGammelTabell),",
              "        OverforingerNyTabell,",
              "        OverforingerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR LonnOgOppgGodtgjorelserGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Lønnsutgifter og oppgavepliktige godtgjørelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR LonnOgOppgGodtgjorelserNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Lønnsutgifter og oppgavepliktige godtgjørelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(LonnOgOppgGodtgjorelserGammelTabell),",
              "        LonnOgOppgGodtgjorelserNyTabell,",
              "        LonnOgOppgGodtgjorelserGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avskrivninger (D) - A590 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR AvskrivningerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Avskrivninger (D)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AvskrivningerNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Avskrivninger (D)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(AvskrivningerGammelTabell),",
              "        AvskrivningerNyTabell,",
              "        AvskrivningerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR SumDriftsinntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Sum driftsinntekter (A)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SumDriftsinntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Sum driftsinntekter (A)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SumDriftsinntekterGammelTabell),",
              "        SumDriftsinntekterNyTabell,",
              "        SumDriftsinntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Resultat eksterne finanstransaksjoner/Netto finansutgifter - AGD22/AGD85 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR NettoFinansUtgifterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Resultat eksterne finanstransaksjoner (H=E-F-G)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR NettoFinansUtgifterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Netto finansutgifter (E)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(NettoFinansUtgifterGammelTabell),",
              "        NettoFinansUtgifterNyTabell,",
              "        NettoFinansUtgifterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG28 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes renteutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes renteinntekter fra egen/deltakende (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes renteutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes renteinntekter fra egen/deltakende (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG31 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes renteutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens renteinntekter fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes renteutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens renteinntekter fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG32 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes avdragutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens mottatte avdrag på interne utlån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes avdragutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens mottatte avdrag på interne utlån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG33 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes utlån til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens bruk av interne lån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes utlån til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens bruk av interne lån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Artnavn",
            "dataType": "string",
            "sourceColumn": "Artnavn"
          },
          {
            "name": "ArtkodeNavn",
            "dataType": "string",
            "sourceColumn": "ArtkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Art = Source{[Schema=\"dbo\",Item=\"Art\"]}[Data]",
                "in",
                "    dbo_Art"
              ]
            }
          }
        ]
      },
      {
        "name": "Balansedata",
        "columns": [
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Balansedatanavn",
            "dataType": "string",
            "sourceColumn": "Balansedatanavn"
          },
          {
            "name": "BalansedatakodeNavn",
            "dataType": "string",
            "sourceColumn": "BalansedatakodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Balansedata = Source{[Schema=\"dbo\",Item=\"Balansedata\"]}[Data]",
                "in",
                "    dbo_Balansedata"
              ]
            }
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Funksjonnavn",
            "dataType": "string",
            "sourceColumn": "Funksjonnavn"
          },
          {
            "name": "FunksjonkodeNavn",
            "dataType": "string",
            "sourceColumn": "FunksjonkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Funksjon = Source{[Schema=\"dbo\",Item=\"Funksjon\"]}[Data]",
                "in",
                "    dbo_Funksjon"
              ]
            }
          }
        ]
      },
      {
        "name": "Kilde",
        "columns": [
          {
            "name": "Kildekode",
            "dataType": "string",
            "sourceColumn": "Kildekode"
          },
          {
            "name": "Kildenavn",
            "dataType": "string",
            "sourceColumn": "Kildenavn"
          },
          {
            "name": "KildekodeNavn",
            "dataType": "string",
            "sourceColumn": "KildekodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Kilde = Source{[Schema=\"dbo\",Item=\"Kilde\"]}[Data]",
                "in",
                "    dbo_Kilde"
              ]
            }
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Regnskapsbegrep",
        "columns": [
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Regnskapsbegrepnavn",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepnavn"
          },
          {
            "name": "RegnskapsbegrepkodeNavn",
            "dataType": "string",
            "sourceColumn": "RegnskapsbegrepkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Regnskapsbegrep = Source{[Schema=\"dbo\",Item=\"Regnskapsbegrep\"]}[Data]",
                "in",
                "    dbo_Regnskapsbegrep"
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Kilde",
            "dataType": "string",
            "sourceColumn": "Kilde"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Variabelkode",
            "dataType": "string",
            "sourceColumn": "Variabelkode"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "KOMØK Indikatorer",
        "columns": [
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Hovedtall",
            "dataType": "int64",
            "sourceColumn": "Hovedtall"
          },
          {
            "name": "Tjenesteområder",
            "dataType": "int64",
            "sourceColumn": "Tjenesteområder"
          },
          {
            "name": "Øko- Oversikt",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt"
          },
          {
            "name": "Øko- Oversikt ekskl foretak",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt ekskl foretak"
          },
          {
            "name": "Indeksert",
            "dataType": "string",
            "sourceColumn": "Indeksert"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_KOMØK Indikatorer\" = Source{[Schema=\"dbo\",Item=\"KOMØK Indikatorer\"]}[Data]",
                "in",
                "    #\"dbo_KOMØK Indikatorer\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Netto driftsresultat i prosent av brutto driftsinntekter",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364], [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 3",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Disposisjonsfond korrigert for årets netto merforbuk i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Disposisjonsfond (K) - 56 - 12364]) || ",
              "                ISBLANK([Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364])",
              "",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Disposisjonsfond (K) - 56 - 12364] ",
              "                    + [Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Korrigert netto driftsresultat i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364])",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364] ",
              "                    + [Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke =",
              "    ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) ||",
              "    ISBLANK([Grunntall - Utlån - 22/KG48 - 12177/13202]) ||",
              "    ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) ||",
              "    ISBLANK([Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202])",
              "    ",
              "RETURN(",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "                - [Grunntall - Utlån - 22/KG48 - 12177/13202] ",
              "                - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Renteeksponert lånegjeld i prosent av langsiktig lånegjeld",
            "expression": [
              "",
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) || ",
              "                ISBLANK([Grunntall - Renteeksponert gjeld - KG39 - 12364])",
              "",
              "RETURN(",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Renteeksponert gjeld - KG39 - 12364], ",
              "                    [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) * 100, ",
              "        8)",
              "    )",
              ")",
              ""
            ]
          },
          {
            "name": "Korrigert netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR Pre2020 = ",
              "        DIVIDE(",
              "            [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "            - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "            - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "            - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202] ",
              "            - [Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177] ",
              "            - [Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202], ",
              "                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "        )",
              "",
              "VAR Post2020 = ",
              "        DIVIDE(",
              "            [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "            - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "            - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "            - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]",
              "            - [Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202], ",
              "                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "        )",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) ||",
              "                ISBLANK([Grunntall - Utlån - 22/KG48 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177]) ||",
              "                ISBLANK([Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "VAR Resultat = ",
              "    IF(",
              "        ValgtAar < 2020,",
              "        Pre2020,",
              "        Post2020",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat * 100, 8)",
              ")"
            ]
          },
          {
            "name": "Inntektssammensetning - Skatt",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218]) ||",
              "                ISBLANK([Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218]) ||",
              "                ISBLANK([Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2])",
              "",
              "VAR SkattSum = [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218] ",
              "               + [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218]",
              "               + [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2]",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(SkattSum, 3)",
              "    )",
              ")"
            ]
          },
          {
            "name": "Inntektssammensetning - Andre Inntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AndreInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre salgs- og leieinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingsInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringsinntekter med krav til motytelse i drift\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AndreOverforingerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre overføringer\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerOgTilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringer og tilskudd fra andre\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SalgsLeieinntekterDriftNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Salgs- og leieinntekter i driftsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brukerbetalinger - A600 - 12328/13218]) ||",
              "                ISBLANK(AndreInntekterGammelTabell) ||",
              "                ISBLANK(OverforingsInntekterGammelTabell) ||",
              "                ISBLANK(AndreOverforingerGammelTabell) ||",
              "                ISBLANK(OverforingerOgTilskuddNyTabell) ||",
              "                ISBLANK(SalgsLeieinntekterDriftNyTabell) ",
              "",
              "VAR Pre2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13218]",
              "                        + AndreInntekterGammelTabell",
              "                        + AndreOverforingerGammelTabell",
              "                        + OverforingsInntekterGammelTabell",
              "",
              "VAR Post2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13218]",
              "                        + OverforingerOgTilskuddNyTabell",
              "                        + SalgsLeieinntekterDriftNyTabell",
              "",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020Resultat,",
              "        Post2020Resultat",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 3)",
              ")",
              "        ",
              "    ",
              "",
              "    "
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter",
            "expression": [
              "",
              "",
              "VAR EtAarSiden = YEAR(TODAY()) - 1",
              "VAR ToAarSiden = YEAR(TODAY()) - 2",
              "VAR TreAarSiden = YEAR(TODAY()) - 3",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = TreAarSiden)",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = ToAarSiden)",
              "    )",
              "",
              "VAR SumEtAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = EtAarSiden)",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR ResultatToAarSiden = ResultatTreAarSiden + DIVIDE((SumToAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "VAR ResultatEtAarSiden = ResultatTreAarSiden + DIVIDE((SumEtAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "",
              "VAR Resultat = ",
              "    SWITCH(",
              "        ValgtAar,",
              "        TreAarSiden, ResultatTreAarSiden,",
              "        ToAarSiden, ResultatToAarSiden,",
              "        EtAarSiden, ResultatEtAarSiden",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 3)",
              ")",
              "            "
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst",
            "expression": [
              " ",
              "",
              ""
            ]
          },
          {
            "name": "Vekst i lønnsutgifter (eks. sosiale utgifter) i faste priser",
            "expression": [
              "",
              ""
            ]
          },
          {
            "name": "Brutto driftsresultat (før avskrivninger) i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "",
              "VAR BruttoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brutto driftsresultat (D=A-B-C)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        (BruttoDriftsresultat + [Grunntall - Avskrivninger (D) - A590 - 12328/13218]) * 100,",
              "        ([Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto finansutgifter i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        -([Grunntall - Resultat eksterne finanstransaksjoner/Netto finansutgifter - AGD22/AGD85 - 12328/13218]",
              "            - [Grunntall - AG28 - 12328/13218]",
              "            - [Grunntall - AG29 - 12328/13218]",
              "            - [Grunntall - AG30 - 12328/13218]",
              "            - [Grunntall - AG31 - 12328/13218]",
              "            - [Grunntall - AG32 - 12328/13218]",
              "            - [Grunntall - AG33 - 12328/13218]",
              "        ) * 100,",
              "        ([Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218]",
              "        )",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Handlingsrom (justert netto driftsresultat i prosent av driftsinntekter)",
            "expression": [
              "",
              "",
              "VAR NettoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] IN {\"Netto driftsresultat (J=D+H+i)\", \"Netto driftsresultat (H=D+E+f+G)\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AvsetningerTilBundneFondGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Avsetninger til bundne fond\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR BrukAvBundneFondGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Bruk av bundne fond\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR NettoAvsetningerTilBundneDriftsfondNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Netto avsetninger til eller bruk av bundne driftsfond\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DekningAvMerforbruk = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] IN {\"Dekning av tidligere års merforbruk og udekket beløp (K)\", \"Dekning av tidligere års merforbruk\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelTabellResultat = ",
              "    DIVIDE(",
              "        (NettoDriftsresultat",
              "        + (AvsetningerTilBundneFondGammelTabell - BrukAvBundneFondGammelTabell)",
              "        + DekningAvMerforbruk), 2)",
              "",
              "Return(BLANK())",
              ""
            ]
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "int64",
            "sourceColumn": "År"
          },
          {
            "name": "Årstall",
            "dataType": "string",
            "sourceColumn": "Årstall"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4b50dd00-2bc4-4226-adcc-afaa2264d904",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Artkode"
      },
      {
        "name": "87d53ce4-13d4-42dc-a0b7-9f6290a6002f",
        "fromTable": "Alle Data",
        "fromColumn": "Kildekode",
        "toTable": "Kilde",
        "toColumn": "Kildekode"
      },
      {
        "name": "ae3dd9e0-6391-4873-814f-f546be9d43af",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "a6a9ef68-bc24-4753-97f0-be9763912084",
        "fromTable": "Alle Data",
        "fromColumn": "Regnskapsbegrepkode",
        "toTable": "Regnskapsbegrep",
        "toColumn": "Regnskapsbegrepkode"
      },
      {
        "name": "d4c5cb7e-0dac-44d5-a7c7-dedcbeec0f20",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "39c4585f-88df-4c90-ba29-7001f983e9ba",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabelkode"
      },
      {
        "name": "bd66c095-a64b-4453-952a-4fe6eb88af22",
        "fromTable": "Alle Data",
        "fromColumn": "Balansedatakode",
        "toTable": "Balansedata",
        "toColumn": "Balansedatakode"
      },
      {
        "name": "06c4c976-b83f-42c4-90bf-3bd377e09189",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Funksjonkode"
      },
      {
        "name": "174104c3-8d7d-42f6-91f0-91c9e1a69e8a",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      }
    ],
    "roles": [
      {
        "name": "Brukere",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "I04\\VK.DB.VK-SXD0E-002_KOMOK.DBO",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1078585"
          }
        ]
      },
      {
        "name": "PowerBI",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "I04\\vk-PowerBIService",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1042837"
          }
        ]
      },
      {
        "name": "API",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}