{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "nb-NO",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/vk-sxd0e-002;Reporting_KOMOK",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "vk-sxd0e-002",
            "database": "Reporting_KOMOK"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "vk-sxd0e-002;Reporting_KOMOK",
          "Username": "hama.keli@ks.no",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Alle Data",
        "columns": [
          {
            "name": "Tabell",
            "dataType": "string",
            "sourceColumn": "Tabell"
          },
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Variabel",
            "dataType": "string",
            "sourceColumn": "Variabel"
          },
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "År",
            "dataType": "string",
            "sourceColumn": "År"
          },
          {
            "name": "Verdi",
            "dataType": "double",
            "sourceColumn": "Verdi"
          },
          {
            "type": "calculated",
            "name": "Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "",
              "",
              ""
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_Alle Data\" = Source{[Schema=\"dbo\",Item=\"Alle Data\"]}[Data]",
                "in",
                "    #\"dbo_Alle Data\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum dataverdi",
            "expression": "SUM('Alle Data'[Verdi])"
          },
          {
            "name": "Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364",
            "expression": [
              "",
              "",
              "VAR BruttoDriftsinntekterIAlt = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Brutto driftsinntekter i alt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(BruttoDriftsinntekterIAlt)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UbrukteLaaneMidlerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Memoriakonto for ubrukte lånemidler (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbrukteLaaneMidlerNyTabell =  ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"F.1.1 Ubrukte lånemidler\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(UbrukteLaaneMidlerGammelTabell),",
              "        UbrukteLaaneMidlerNyTabell,",
              "        UbrukteLaaneMidlerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)",
              ""
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Valgt regionkode",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "RETURN(SelectedRegion)"
            ]
          },
          {
            "name": "Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202",
            "expression": [
              "",
              "",
              "",
              "VAR UbundetInvesteringsFondGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Ubundne investeringsfond (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UbundetInvesteringsFondNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"C.2.1 Ubundet investeringsfond\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UbundetInvesteringsFondGammelTabell),",
              "        UbundetInvesteringsFondNyTabell,",
              "        UbundetInvesteringsFondGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Udekket beløp i investeringsregnskapet (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UdekketBelopIInvesteringsregnskapetNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"C.2.3 Udekket beløp i investeringsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UdekketBelopIInvesteringsregnskapetGammelTabell),",
              "        UdekketBelopIInvesteringsregnskapetNyTabell,",
              "        UdekketBelopIInvesteringsregnskapetGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Netto Driftsresultat - AGD23 - 12364",
            "expression": [
              "",
              "",
              "VAR NettoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Netto driftsresultat\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(NettoDriftsresultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Disposisjonsfond (K) - 56 - 12364",
            "expression": [
              "",
              "",
              "VAR Disposisjonsfond = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Disposisjonsfond (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(Disposisjonsfond)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364",
            "expression": [
              "",
              "",
              "VAR AaretsMerforbrukIDriftsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]),[Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Årets merforbruk i driftsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AaretsMerforbrukIDriftsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364",
            "expression": [
              "",
              "",
              "VAR AvsetningTilBundneFondNetto = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Avsetning til bundne fond (netto)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = AvsetningTilBundneFondNetto",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Utlån - 22/KG48 - 12177/13202",
            "expression": [
              "",
              "",
              "VAR SelectedRegion = SELECTEDVALUE(Region[Kode])",
              "",
              "VAR UtlaanGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Utlån (anleggsmidler)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR UtlaanNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13202\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"A.2.3 Utlån\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    ) ",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(UtlaanGammelTabell),",
              "        UtlaanNyTabell,",
              "        UtlaanGammelTabell",
              "    )",
              "",
              "RETURN(",
              "    Resultat",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364",
            "expression": [
              "",
              "",
              "VAR LangsiktigGjeldEkslPensjonsforpliktelser =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Langsiktig gjeld ekskl. pensjonsforpliktelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "RETURN(",
              "    LangsiktigGjeldEkslPensjonsforpliktelser",
              ")"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Renteeksponert gjeld - KG39 - 12364",
            "expression": [
              "",
              "",
              "VAR RenteeksponertGjeld = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Regnskapsbegrepnavn]), [Regnskapsbegrepnavn] = \"Renteeksponert gjeld\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(RenteeksponertGjeld)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177",
            "expression": [
              "",
              "",
              "VAR UdisponertIInvesteringsregnskapet = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12177\"),",
              "        FILTER(ALL(Balansedata[Balansedatanavn]), [Balansedatanavn] = \"Udisponert i investeringsregnskapet (K)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(UdisponertIInvesteringsregnskapet)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Rammetilskudd - A800 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR RammetilskuddGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]),  [Artnavn] = \"Rammetilskudd\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR RammetilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]),  [Artnavn] = \"Rammetilskudd\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(RammetilskuddGammelTabell),",
              "        RammetilskuddNyTabell,",
              "        RammetilskuddGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR SkattGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Skatt på inntekt og formue\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkattNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Inntekts- og formueskatt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkattGammelTabell),",
              "        SkattNyTabell,",
              "        SkattGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR EiendomsskattTotalGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Eiendomsskatt totalt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR EiendomsskattTotalNyTabelll =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Eiendomsskatt totalt\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(EiendomsskattTotalGammelTabell),",
              "        EiendomsskattTotalNyTabelll,",
              "        EiendomsskattTotalGammelTabell",
              "    )",
              "",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2",
            "expression": [
              "",
              "",
              "VAR SkatteInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre direkte og indirekte skatter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SkatteInntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre skatteinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SkatteInntekterGammelTabell),",
              "        SkatteInntekterNyTabell,",
              "        SkatteInntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Brukerbetalinger - A600 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR BrukerbetalingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brukerbetalinger\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR BrukerbetalingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brukerbetalinger\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(BrukerbetalingerGammelTabell),",
              "        BrukerbetalingerNyTabell,",
              "        BrukerbetalingerGammelTabell",
              "    )",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Andre statlige overføringer - A810/AGD77 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR OverforingerGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre statlige overføringer\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerNyTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre overføringer og tilskudd fra staten\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(OverforingerGammelTabell),",
              "        OverforingerNyTabell,",
              "        OverforingerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR LonnOgOppgGodtgjorelserGammelTabell =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Lønnsutgifter og oppgavepliktige godtgjørelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR LonnOgOppgGodtgjorelserNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Lønnsutgifter og oppgavepliktige godtgjørelser\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(LonnOgOppgGodtgjorelserGammelTabell),",
              "        LonnOgOppgGodtgjorelserNyTabell,",
              "        LonnOgOppgGodtgjorelserGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Avskrivninger (D) - A590 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR AvskrivningerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Avskrivninger (D)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AvskrivningerNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Avskrivninger (D)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(AvskrivningerGammelTabell),",
              "        AvskrivningerNyTabell,",
              "        AvskrivningerGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR SumDriftsinntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Sum driftsinntekter (A)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SumDriftsinntekterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Sum driftsinntekter (A)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(SumDriftsinntekterGammelTabell),",
              "        SumDriftsinntekterNyTabell,",
              "        SumDriftsinntekterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes kjøp fra egen (fylkes-)kommune og (fylkes-)kommunens salg til IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KFenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer til egne FKF/KF\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12320/13178",
            "expression": [
              " ",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom IKSenes overføringer til egen (fylkes-)kommune og (fylkes-)kommunens overføringer fra IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Resultat eksterne finanstransaksjoner/Netto finansutgifter - AGD22/AGD85 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR NettoFinansUtgifterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Resultat eksterne finanstransaksjoner (H=E-F-G)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR NettoFinansUtgifterNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Netto finansutgifter (E)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(NettoFinansUtgifterGammelTabell),",
              "        NettoFinansUtgifterNyTabell,",
              "        NettoFinansUtgifterGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG28 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes renteutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes renteinntekter fra egen/deltakende (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes renteutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes renteinntekter fra egen/deltakende (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG31 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes renteutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens renteinntekter fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes renteutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens renteinntekter fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG32 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes avdragutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens mottatte avdrag på interne utlån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes avdragutgifter til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens mottatte avdrag på interne utlån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG33 - 12328/13218",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes utlån til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens bruk av interne lån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom FKF/KF/IKSenes utlån til egen/deltakende (fylkes-)kommune og (fylkes-)kommunens bruk av interne lån fra egne/deltakende FKF/KF/IKS\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG29 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes avdragsutgifter til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKSenes mottatte avdrag på utlån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat =",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - AG30 - 12320/13178",
            "expression": [
              "",
              "",
              "VAR DifferanseGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12320\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DifferanseNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Differansen mellom (fylkes-)kommunes utlån til egne FKF/KF og IKS de er deltaker i og FKF/KF/IKS enes bruk av interne lån fra egen (fylkes-)kommune\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ISBLANK(DifferanseGammelTabell),",
              "        DifferanseNyTabell,",
              "        DifferanseGammelTabell",
              "    )",
              "",
              "RETURN(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Befolkning - tre år siden",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(LEFT(SELECTEDVALUE('År'[År]), 4))",
              "",
              "VAR TreAarSiden = FORMAT(ValgtAar - 2, \"####K3\")",
              "",
              "VAR Resultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"01222\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Befolkning ved inngangen av kvartalet\"),",
              "        FILTER(ALL('År'[År]), [År] = TreAarSiden)",
              "    )",
              "",
              "return(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Befolkning - to år siden",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(LEFT(SELECTEDVALUE('År'[År]), 4))",
              "",
              "VAR ToAarSiden = FORMAT(ValgtAar - 1, \"####K3\")",
              "",
              "VAR Resultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"01222\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Befolkning ved inngangen av kvartalet\"),",
              "        FILTER(ALL('År'[År]), [År] = ToAarSiden)",
              "    )",
              "",
              "return(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Befolkning - et år siden",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(LEFT(SELECTEDVALUE('År'[År]), 4))",
              "",
              "VAR EtAarSiden = FORMAT(ValgtAar, \"####K3\")",
              "",
              "VAR Resultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"01222\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Befolkning ved inngangen av kvartalet\"),",
              "        FILTER(ALL('År'[År]), [År] = EtAarSiden)",
              "    )",
              "",
              "return(Resultat)"
            ],
            "displayFolder": "Grunntall"
          },
          {
            "name": "Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364",
            "expression": [
              "",
              "",
              "VAR AGI1 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AGI1\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "RETURN(AGI1)"
            ],
            "displayFolder": "Grunntall"
          }
        ]
      },
      {
        "name": "Art",
        "columns": [
          {
            "name": "Artkode",
            "dataType": "string",
            "sourceColumn": "Artkode"
          },
          {
            "name": "Artnavn",
            "dataType": "string",
            "sourceColumn": "Artnavn"
          },
          {
            "name": "ArtkodeNavn",
            "dataType": "string",
            "sourceColumn": "ArtkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Art = Source{[Schema=\"dbo\",Item=\"Art\"]}[Data]",
                "in",
                "    dbo_Art"
              ]
            }
          }
        ]
      },
      {
        "name": "Balansedata",
        "columns": [
          {
            "name": "Balansedatakode",
            "dataType": "string",
            "sourceColumn": "Balansedatakode"
          },
          {
            "name": "Balansedatanavn",
            "dataType": "string",
            "sourceColumn": "Balansedatanavn"
          },
          {
            "name": "BalansedatakodeNavn",
            "dataType": "string",
            "sourceColumn": "BalansedatakodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Balansedata = Source{[Schema=\"dbo\",Item=\"Balansedata\"]}[Data]",
                "in",
                "    dbo_Balansedata"
              ]
            }
          }
        ]
      },
      {
        "name": "Funksjon",
        "columns": [
          {
            "name": "Funksjonkode",
            "dataType": "string",
            "sourceColumn": "Funksjonkode"
          },
          {
            "name": "Funksjonnavn",
            "dataType": "string",
            "sourceColumn": "Funksjonnavn"
          },
          {
            "name": "FunksjonkodeNavn",
            "dataType": "string",
            "sourceColumn": "FunksjonkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Funksjon = Source{[Schema=\"dbo\",Item=\"Funksjon\"]}[Data]",
                "in",
                "    dbo_Funksjon"
              ]
            }
          }
        ]
      },
      {
        "name": "Region",
        "columns": [
          {
            "name": "Kode",
            "dataType": "string",
            "sourceColumn": "Kode"
          },
          {
            "name": "Navn",
            "dataType": "string",
            "sourceColumn": "Navn"
          },
          {
            "name": "KodeNummernavn",
            "dataType": "string",
            "sourceColumn": "KodeNummernavn"
          },
          {
            "name": "Regionnummer",
            "dataType": "string",
            "sourceColumn": "Regionnummer"
          },
          {
            "name": "Kategori",
            "dataType": "string",
            "sourceColumn": "Kategori"
          },
          {
            "name": "GyldigFraDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigFraDato"
          },
          {
            "name": "GyldigTilDato",
            "dataType": "dateTime",
            "sourceColumn": "GyldigTilDato"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Region = Source{[Schema=\"dbo\",Item=\"Region\"]}[Data]",
                "in",
                "    dbo_Region"
              ]
            }
          }
        ]
      },
      {
        "name": "Regnskapsbegrep",
        "columns": [
          {
            "name": "Regnskapsbegrepkode",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepkode"
          },
          {
            "name": "Regnskapsbegrepnavn",
            "dataType": "string",
            "sourceColumn": "Regnskapsbegrepnavn"
          },
          {
            "name": "RegnskapsbegrepkodeNavn",
            "dataType": "string",
            "sourceColumn": "RegnskapsbegrepkodeNavn"
          },
          {
            "name": "Tabellkode",
            "dataType": "string",
            "sourceColumn": "Tabellkode"
          },
          {
            "name": "Original dimensjonskode",
            "dataType": "string",
            "sourceColumn": "Original dimensjonskode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Regnskapsbegrep = Source{[Schema=\"dbo\",Item=\"Regnskapsbegrep\"]}[Data]",
                "in",
                "    dbo_Regnskapsbegrep"
              ]
            }
          }
        ]
      },
      {
        "name": "Tabeller",
        "columns": [
          {
            "name": "Tabellnummer",
            "dataType": "string",
            "sourceColumn": "Tabellnummer"
          },
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Kilde",
            "dataType": "string",
            "sourceColumn": "Kilde"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Tabeller = Source{[Schema=\"dbo\",Item=\"Tabeller\"]}[Data]",
                "in",
                "    dbo_Tabeller"
              ]
            }
          }
        ]
      },
      {
        "name": "Variabel",
        "columns": [
          {
            "name": "Gruppe",
            "dataType": "string",
            "sourceColumn": "Gruppe"
          },
          {
            "name": "Variabelkode",
            "dataType": "string",
            "sourceColumn": "Variabelkode"
          },
          {
            "name": "Variabelnavn",
            "dataType": "string",
            "sourceColumn": "Variabelnavn"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_Variabel = Source{[Schema=\"dbo\",Item=\"Variabel\"]}[Data]",
                "in",
                "    dbo_Variabel"
              ]
            }
          }
        ]
      },
      {
        "name": "KOMØK Indikatorer",
        "columns": [
          {
            "name": "Andre",
            "dataType": "int64",
            "sourceColumn": "Andre"
          },
          {
            "name": "Hovedtall",
            "dataType": "int64",
            "sourceColumn": "Hovedtall"
          },
          {
            "name": "Tjenesteområder",
            "dataType": "int64",
            "sourceColumn": "Tjenesteområder"
          },
          {
            "name": "Øko- Oversikt",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt"
          },
          {
            "name": "Øko- Oversikt ekskl foretak",
            "dataType": "int64",
            "sourceColumn": "Øko- Oversikt ekskl foretak"
          },
          {
            "name": "Indeksert",
            "dataType": "string",
            "sourceColumn": "Indeksert"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    #\"dbo_KOMØK Indikatorer\" = Source{[Schema=\"dbo\",Item=\"KOMØK Indikatorer\"]}[Data]",
                "in",
                "    #\"dbo_KOMØK Indikatorer\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Netto driftsresultat i prosent av brutto driftsinntekter",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364], [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 3",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Disposisjonsfond korrigert for årets netto merforbuk i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Disposisjonsfond (K) - 56 - 12364]) || ",
              "                ISBLANK([Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364])",
              "",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Disposisjonsfond (K) - 56 - 12364] ",
              "                    + [Grunntall - Årets merforbruk i driftsregnskapet - AGD29 - 12364], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Korrigert netto driftsresultat i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) || ",
              "                ISBLANK([Grunntall - Netto Driftsresultat - AGD23 - 12364]) || ",
              "                ISBLANK([Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364])",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364] ",
              "                    + [Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              " ",
              "",
              "VAR HarBlanke =",
              "    ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) ||",
              "    ISBLANK([Grunntall - Utlån - 22/KG48 - 12177/13202]) ||",
              "    ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) ||",
              "    ISBLANK([Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202])",
              "    ",
              "RETURN(",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "                - [Grunntall - Utlån - 22/KG48 - 12177/13202] ",
              "                - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202], ",
              "                    [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100, 8",
              "        )",
              "    )",
              ")"
            ]
          },
          {
            "name": "Renteeksponert lånegjeld i prosent av langsiktig lånegjeld",
            "expression": [
              "",
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) || ",
              "                ISBLANK([Grunntall - Renteeksponert gjeld - KG39 - 12364])",
              "",
              "RETURN(",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(",
              "            DIVIDE([Grunntall - Renteeksponert gjeld - KG39 - 12364], ",
              "                    [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) * 100, ",
              "        8)",
              "    )",
              ")",
              ""
            ]
          },
          {
            "name": "Korrigert netto lånegjeld i prosent av brutto driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR Pre2020 = ",
              "        DIVIDE(",
              "            [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "            - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "            - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "            - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202] ",
              "            - [Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177] ",
              "            - [Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202], ",
              "                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "        )",
              "",
              "VAR Post2020 = ",
              "        DIVIDE(",
              "            [Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364] ",
              "            - [Grunntall - Utlån - 22/KG48 - 12177/13202]",
              "            - [Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202] ",
              "            - [Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]",
              "            - [Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202], ",
              "                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]",
              "        )",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Langsiktig gjeld ekskl. pensjonsforpliktelser - KG32 - 12364]) ||",
              "                ISBLANK([Grunntall - Utlån - 22/KG48 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Ubrukte lånemidler - 9100/KG92 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Ubundet investeringsfond - 53/KG69 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Udisponert i investeringsregnskapet (K) - 5960 - 12177]) ||",
              "                ISBLANK([Grunntall - Udekket beløp i investeringsregnskapet - 5970/KG71 - 12177/13202]) ||",
              "                ISBLANK([Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364])",
              "",
              "VAR Resultat = ",
              "    IF(",
              "        ValgtAar < 2020,",
              "        Pre2020,",
              "        Post2020",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat * 100, 8)",
              ")"
            ]
          },
          {
            "name": "Inntektssammensetning - Skatt",
            "expression": [
              "",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218]) ||",
              "                ISBLANK([Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218]) ||",
              "                ISBLANK([Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2])",
              "",
              "VAR SkattSum = [Grunntall - Skatt på inntekt og formue/Inntekts- og formueskatt - A870/AGD75 - 12328/13218] ",
              "               + [Grunntall - Eiendomsskatt totalt - AG10 - 12328/13218]",
              "               + [Grunntall - Andre direkte og indirekte skatter/Andre skatteinntekter - 877/AGD76 - 12328/13218 v2]",
              "",
              "RETURN (",
              "    IF(HarBlanke,",
              "        BLANK(),",
              "        ROUND(SkattSum, 3)",
              "    )",
              ")"
            ]
          },
          {
            "name": "Inntektssammensetning - Andre Inntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AndreInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre salgs- og leieinntekter\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingsInntekterGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringsinntekter med krav til motytelse i drift\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AndreOverforingerGammelTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Andre overføringer\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR OverforingerOgTilskuddNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Overføringer og tilskudd fra andre\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR SalgsLeieinntekterDriftNyTabell = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Salgs- og leieinntekter i driftsregnskapet\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR HarBlanke = ISBLANK([Grunntall - Brukerbetalinger - A600 - 12328/13218]) ||",
              "                ISBLANK(AndreInntekterGammelTabell) ||",
              "                ISBLANK(OverforingsInntekterGammelTabell) ||",
              "                ISBLANK(AndreOverforingerGammelTabell) ||",
              "                ISBLANK(OverforingerOgTilskuddNyTabell) ||",
              "                ISBLANK(SalgsLeieinntekterDriftNyTabell) ",
              "",
              "VAR Pre2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13218]",
              "                        + AndreInntekterGammelTabell",
              "                        + AndreOverforingerGammelTabell",
              "                        + OverforingsInntekterGammelTabell",
              "",
              "VAR Post2020Resultat = [Grunntall - Brukerbetalinger - A600 - 12328/13218]",
              "                        + OverforingerOgTilskuddNyTabell",
              "                        + SalgsLeieinntekterDriftNyTabell",
              "",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020Resultat,",
              "        Post2020Resultat",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 3)",
              ")",
              "        ",
              "    ",
              "",
              "    "
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR EtAarSiden = 2019",
              "VAR ToAarSiden = 2019 - 1",
              "VAR TreAarSiden = 2019 - 2",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(TreAarSiden, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ToAarSiden, \"####\"))",
              "    )",
              "",
              "",
              "VAR SumEtAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(EtAarSiden, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR ResultatToAarSiden = ResultatTreAarSiden + DIVIDE((SumToAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "VAR ResultatEtAarSiden = ResultatTreAarSiden + DIVIDE((SumEtAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "",
              "VAR Resultat = ",
              "    SWITCH(",
              "        ValgtAar,",
              "        TreAarSiden, ResultatTreAarSiden,",
              "        ToAarSiden, ResultatToAarSiden,",
              "        EtAarSiden, ResultatEtAarSiden",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")",
              "            "
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Deflatert",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR EtAarSiden = 2019",
              "VAR ToAarSiden = 2019 - 1",
              "VAR TreAarSiden = 2019 - 2",
              "",
              "VAR PrisvekstEtAarSiden = 1.053",
              "VAR PrisvekstToAarSiden = 1.024",
              "VAR PrisvekstTreAarSiden = 1.000",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(TreAarSiden, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ToAarSiden, \"####\"))",
              "    )",
              "",
              "VAR SumEtAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(EtAarSiden, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR ResultatToAarSiden = ResultatTreAarSiden + DIVIDE((DIVIDE(SumToAarSiden, PrisvekstToAarSiden) - DIVIDE(SumTreAarSiden, PrisvekstTreAarSiden)) * 100,",
              "                                               DIVIDE(SumTreAarSiden, PrisvekstTreAarSiden))",
              "",
              "VAR ResultatEtAarSiden = ResultatTreAarSiden + DIVIDE((DIVIDE(SumEtAarSiden, PrisvekstEtAarSiden) - DIVIDE(SumToAarSiden, PrisvekstToAarSiden)) * 100,",
              "                                               DIVIDE(SumToAarSiden, PrisvekstToAarSiden))",
              "",
              "VAR Resultat = ",
              "    SWITCH(",
              "        ValgtAar,",
              "        TreAarSiden, ResultatTreAarSiden,",
              "        ToAarSiden, ResultatToAarSiden,",
              "        EtAarSiden, ResultatEtAarSiden",
              "    )",
              "",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Vekst i lønnsutgifter (eks. sosiale utgifter) i faste priser",
            "expression": [
              "",
              ""
            ]
          },
          {
            "name": "Brutto driftsresultat (før avskrivninger) i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "",
              "VAR BruttoDriftsresultat = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Artnavn]), [Artnavn] = \"Brutto driftsresultat (D=A-B-C)\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        (BruttoDriftsresultat + [Grunntall - Avskrivninger (D) - A590 - 12328/13218]) * 100,",
              "        ([Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto finansutgifter i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    DIVIDE(",
              "        -([Grunntall - Resultat eksterne finanstransaksjoner/Netto finansutgifter - AGD22/AGD85 - 12328/13218]",
              "            - [Grunntall - AG28 - 12328/13218]",
              "            - [Grunntall - AG29 - 12328/13218]",
              "            - [Grunntall - AG30 - 12328/13218]",
              "            - [Grunntall - AG31 - 12328/13218]",
              "            - [Grunntall - AG32 - 12328/13218]",
              "            - [Grunntall - AG33 - 12328/13218]",
              "        ) * 100,",
              "        ([Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218]",
              "        )",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Handlingsrom (justert netto driftsresultat i prosent av driftsinntekter)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AGD66orAGD89 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AGD66\", \"AGD89\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM550 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"550\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM950 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"950\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD91 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD91\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM530orAD350 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"530\", \"AD530\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelDelEn = ",
              "    AGD66orAGD89",
              "    + (DIM950 - DIM550)",
              "    + DIM530orAD350",
              "",
              "VAR DelTo = [Handlingsrom - Avskrivninger minus Avdrag]",
              "",
              "VAR DelTre =",
              "        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218]",
              "    ",
              "",
              "VAR Resultat = ",
              "    DIVIDE((GammelDelEn + DelTo) * 100, DelTre)",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Investeringsutgifter i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR SumInvesteringsUtgifter = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AGI20\", \"AGI43\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG19 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG19\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG20 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG20\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG21 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG21\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG22 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG22\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "",
              "VAR Resultat = ",
              "    DIVIDE((SumInvesteringsUtgifter + AG19 + AG20 + AG21 + AG22) * 100,",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "            - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12320/13178]",
              "            - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12320/13178]",
              "            - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12320/13178]",
              "            - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12320/13178])",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Netto bruk av lån i prosent av driftsinntekter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AGI41or529 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"529\", \"AGI41\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6orAGI42 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AG6\", \"AGI42\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM929 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"929\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13orAGI46 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AG13\", \"AGI46\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGI17 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI17\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM522 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"522\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM912 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"912\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM512 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"512\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM922 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13178\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"922\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG32 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG32\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG33 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12320\", \"13178\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG33\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Pre2020 = ",
              "    DIVIDE(",
              "        (AGI17 + AG13orAGI46 + DIM929 - AGI41or529 - AG6orAGI42 - AG5 ",
              "        - [Grunntall - AG29 - 12320/13178] - [Grunntall - AG30 - 12320/13178] - AG32 - AG33) * 100,",
              "        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12320/13178]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12320/13178]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12320/13178]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12320/13178])",
              "",
              "VAR Post2020 =",
              "    DIVIDE(",
              "        (AGI17 + AG13orAGI46 + DIM929 - AGI41or529 - AG6orAGI42 - AG5 - DIM522 + DIM912 - DIM512 + DIM922",
              "        - [Grunntall - AG29 - 12320/13178] - [Grunntall - AG30 - 12320/13178] - AG32 - AG33) * 100,",
              "        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12320/13178]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12320/13178]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12320/13178]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12320/13178])",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        Pre2020,",
              "        Post2020",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Per innbygger",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR BefolkningsvekstEtAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - et år siden] - [Grunntall - Befolkning - to år siden]),",
              "                                            [Grunntall - Befolkning - to år siden])",
              "VAR BefolkningsvekstToAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - to år siden] - [Grunntall - Befolkning - tre år siden]),",
              "                                            [Grunntall - Befolkning - tre år siden])",
              "VAR BefolkningsvekstForholdstallTreAarSiden= 1.000",
              "",
              "VAR BefolkningsvekstForholdstallToAarSiden = BefolkningsvekstForholdstallTreAarSiden * BefolkningsvekstToAarSiden",
              "",
              "VAR BefolkningsvekstForholdstallEtAarSiden = BefolkningsvekstForholdstallToAarSiden * BefolkningsvekstEtAarSiden",
              "",
              "VAR EtAarSiden = 2019",
              "VAR ToAarSiden = 2019 - 1",
              "VAR TreAarSiden = 2019 - 2",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(TreAarSiden, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ToAarSiden, \"####\"))",
              "    )",
              "",
              "",
              "VAR SumEtAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(EtAarSiden, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR ResultatToAarSiden = ResultatTreAarSiden + DIVIDE((DIVIDE(SumToAarSiden, BefolkningsvekstForholdstallToAarSiden) ",
              "                                             - DIVIDE(SumTreAarSiden, BefolkningsvekstForholdstallTreAarSiden)) * 100, ",
              "                                               DIVIDE(SumTreAarSiden, BefolkningsvekstForholdstallTreAarSiden))",
              "",
              "VAR ResultatEtAarSiden = ResultatTreAarSiden + DIVIDE((DIVIDE(SumEtAarSiden, BefolkningsvekstForholdstallEtAarSiden)",
              "                                             - DIVIDE(SumToAarSiden, BefolkningsvekstForholdstallToAarSiden)) * 100, ",
              "                                               DIVIDE(SumToAarSiden, BefolkningsvekstForholdstallToAarSiden))",
              "",
              "VAR Resultat = ",
              "    SWITCH(",
              "        ValgtAar,",
              "        TreAarSiden, ResultatTreAarSiden,",
              "        ToAarSiden, ResultatToAarSiden,",
              "        EtAarSiden, ResultatEtAarSiden",
              "    )",
              "",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter - To år siden",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR Resultat = ResultatTreAarSiden + DIVIDE((SumToAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")",
              "            "
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter - Et år siden",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR Resultat = ResultatTreAarSiden + DIVIDE((SumEtAarSiden - SumTreAarSiden) * 100, SumTreAarSiden)",
              "",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")",
              "            "
            ]
          },
          {
            "name": "Indeks - Tre år siden",
            "expression": [
              "",
              "",
              "VAR Resultat = 100",
              "",
              "RETURN(100)"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Deflatert - To År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR PrisvekstEtAarSiden = 1.064",
              "VAR PrisvekstToAarSiden = 1.031",
              "VAR PrisvekstTreAarSiden = 1.000",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "VAR Resultat1 = DIVIDE(SumToAarSiden, PrisvekstToAarSiden)",
              "VAR Resultat2 = DIVIDE(SumTreAarSiden, PrisvekstTreAarSiden)",
              "VAR Resultat = DIVIDE(Resultat1 * 100, Resultat2)",
              "",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Deflatert - Et År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR PrisvekstEtAarSiden = 1.064",
              "VAR PrisvekstToAarSiden = 1.031",
              "VAR PrisvekstTreAarSiden = 1.000",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumEtAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR ResultatTreAarSiden = 100",
              "",
              "VAR Resultat1 = DIVIDE(SumEtAarSiden, PrisvekstEtAarSiden)",
              "VAR Resultat2 = DIVIDE(SumTreAarSiden, PrisvekstTreAarSiden)",
              "VAR Resultat = DIVIDE(Resultat1 * 100, Resultat2)",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Nominell vekst i frie inntekter - TEST",
            "expression": [
              "",
              "",
              "VAR Resultat = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt]                ",
              "    )",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Per innb - To År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR BefolkningsvekstEtAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - et år siden] - [Grunntall - Befolkning - to år siden]),",
              "                                            [Grunntall - Befolkning - to år siden])",
              "VAR BefolkningsvekstToAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - to år siden] - [Grunntall - Befolkning - tre år siden]),",
              "                                            [Grunntall - Befolkning - tre år siden])",
              "VAR BefolkningsvekstForholdstallTreAarSiden= 1.000",
              "",
              "VAR BefolkningsvekstForholdstallToAarSiden = BefolkningsvekstForholdstallTreAarSiden * BefolkningsvekstToAarSiden",
              "",
              "VAR BefolkningsvekstForholdstallEtAarSiden = BefolkningsvekstForholdstallToAarSiden * BefolkningsvekstEtAarSiden",
              "",
              "VAR PrisvekstEtAarSiden = 1.064",
              "VAR PrisvekstToAarSiden = 1.031",
              "VAR PrisvekstTreAarSiden = 1.000",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR SumToAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumAlleAar = SumTreAarSiden + SumToAarSiden + SumEtAarSiden",
              "",
              "VAR ResultatTreAarSiden = 100",
              "",
              "VAR Resultat1 = DIVIDE(SumToAarSiden, BefolkningsvekstForholdstallToAarSiden)",
              "VAR Resultat2 = DIVIDE(SumTreAarSiden, BefolkningsvekstForholdstallTreAarSiden)",
              "VAR Resultat = DIVIDE(Resultat1 * 100, Resultat2)",
              "",
              "RETURN(",
              "    ROUND(BefolkningsvekstForholdstallToAarSiden, 3)",
              ")"
            ]
          },
          {
            "name": "Vekst i frie inntekter korrigert for prisstigning og befolkningsvekst - Per innb - Et År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR BefolkningsvekstEtAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - et år siden] - [Grunntall - Befolkning - to år siden]),",
              "                                            [Grunntall - Befolkning - to år siden])",
              "",
              "VAR BefolkningsvekstToAarSiden = 1.000 + DIVIDE(([Grunntall - Befolkning - to år siden] - [Grunntall - Befolkning - tre år siden]),",
              "                                            [Grunntall - Befolkning - tre år siden])",
              "",
              "VAR BefolkningsvekstForholdstallTreAarSiden= 1.000",
              "",
              "VAR BefolkningsvekstForholdstallToAarSiden = BefolkningsvekstForholdstallTreAarSiden * BefolkningsvekstToAarSiden",
              "",
              "VAR BefolkningsvekstForholdstallEtAarSiden = BefolkningsvekstForholdstallToAarSiden * BefolkningsvekstEtAarSiden",
              "",
              "VAR PrisvekstEtAarSiden = 1.064",
              "VAR PrisvekstToAarSiden = 1.031",
              "VAR PrisvekstTreAarSiden = 1.000",
              "",
              "VAR SumEtAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )    ",
              "",
              "VAR SumToAarSiden = ",
              "     CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR SumTreAarSiden = ",
              "    CALCULATE([Grunntall - Rammetilskudd - A800 - 12328/13218]",
              "                + [Inntektssammensetning - Skatt],",
              "                FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )    ",
              "",
              "VAR SumAlleAar = SumTreAarSiden + SumToAarSiden + SumEtAarSiden",
              "",
              "VAR ResultatTreAarSiden = 100",
              "",
              "VAR Resultat1 = DIVIDE(SumEtAarSiden, BefolkningsvekstForholdstallEtAarSiden) ",
              "VAR Resultat2 = DIVIDE(SumTreAarSiden, BefolkningsvekstForholdstallTreAarSiden)",
              "VAR Resultat = DIVIDE(Resultat1 * 100, Resultat2)",
              "",
              "RETURN(",
              "    ROUND(BefolkningsvekstForholdstallEtAarSiden, 3)",
              ")"
            ]
          },
          {
            "name": "Vekst i lønnsutfigter (eks. sosiale utgifter) i faste priser - To År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR LonnsvekstEtAarSiden = 1.063",
              "VAR LonnsvekstToAarSiden = 1.035",
              "VAR LonnsvekstTreAarSiden = 1.000",
              "",
              "VAR AG15_2018 =",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 2, \"####\"))",
              "    )",
              "",
              "VAR AG15_2019 =",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((AG15_2019 * LonnsvekstToAarSiden) * 100, AG15_2018 * LonnsvekstTreAarSiden)",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Vekst i lønnsutfigter (eks. sosiale utgifter) i faste priser - Et År Siden",
            "expression": [
              " ",
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR LonnsvekstEtAarSiden = 1.062945",
              "VAR LonnsvekstToAarSiden = 1.035",
              "VAR LonnsvekstTreAarSiden = 1.000",
              "",
              "VAR AG15_2019 =",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar - 1, \"####\"))",
              "    )",
              "",
              "VAR AG15_2020 =",
              "    CALCULATE([Grunntall - Lønnsutgifter og oppgavepliktige godtgjørelser - AG15 - 12328/13218],",
              "        FILTER(ALL('År'[År]), [År] = FORMAT(ValgtAar, \"####\"))",
              "    )",
              "",
              "VAR Resultat = DIVIDE((AG15_2020 * LonnsvekstEtAarSiden) * 100, AG15_2019 * LonnsvekstToAarSiden)",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Handlingsrom - Avskrivninger minus Avdrag",
            "expression": [
              "",
              "",
              "VAR AG5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AD990orAGD87 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AD990\", \"AGD87\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = (-AD990orAGD87",
              "        - (AG13 - (AG5 + [Grunntall - AG29 - 12328/13218] + [Grunntall - AG32 - 12328/13218]) - AG6)",
              "    )",
              "",
              "RETURN(ROUND(Resultat, 1))"
            ]
          },
          {
            "name": "Handlingsrom - Netto Drift i pst",
            "expression": [
              "",
              "",
              "VAR prosentResultat = DIVIDE([Grunntall - Netto Driftsresultat - AGD23 - 12364], [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100",
              "",
              "RETURN(ROUND(prosentResultat, 1))"
            ]
          },
          {
            "name": "Handlingsrom - Avsetning til bundne fond i pst",
            "expression": [
              "",
              "",
              "VAR prosentResultat = DIVIDE([Grunntall - Avsetning til bundne fond (netto) - AGD74 - 12364], ",
              "                                [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100",
              "",
              "RETURN(ROUND(prosentResultat, 1))"
            ]
          },
          {
            "name": "Handlingsrom - Avskrivninger minus Avdrag i pst",
            "expression": [
              "",
              "",
              "VAR prosentResulat = DIVIDE([Handlingsrom - Avskrivninger minus Avdrag], [Grunntall - Brutto driftsinntekter i alt - AGD13 - 12364]) * 100",
              "",
              "RETURN(ROUND(prosentResulat, 1))"
            ]
          },
          {
            "name": "Handlingsrom (justert netto driftsresultat i Beløp (1000 kr) av driftsinntekter)",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AGD66orAGD89 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"AGD66\", \"AGD89\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM550 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"550\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM950 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"950\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD91 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD91\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM530orAD350 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] IN {\"530\", \"AD530\"}),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelDelEn = ",
              "    AGD66orAGD89",
              "    + (DIM950 - DIM550)",
              "    + DIM530orAD350",
              "",
              "VAR DelTo = [Handlingsrom - Avskrivninger minus Avdrag]",
              "",
              "VAR DelTre =",
              "        [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]",
              "        - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218]",
              "        - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218]",
              "        - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218]",
              "        - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218]",
              "    ",
              "",
              "VAR Resultat = ",
              "    (GammelDelEn + DelTo)",
              "",
              "RETURN(",
              "    ROUND(Resultat, 1)",
              ")"
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Renteinntekt",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG36 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG36\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD79 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD79\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AD905 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AD905\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE((AG36 - AD905) * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]),",
              "        DIVIDE(AGD79 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")",
              "",
              ""
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Utbytte",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AD905 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12364\"),",
              "        FILTER(ALL(Regnskapsbegrep[Original dimensjonskode]), [Original dimensjonskode] = \"AD905\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD81 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD81\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(AD905 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]),",
              "        DIVIDE(AGD81 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Gevinst",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR DIM909 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"909\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM509 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"509\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD83 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD83\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(DIM909 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]),",
              "        DIVIDE(AGD83 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Renteutgifter",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG42 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG42\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM509 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"509\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AGD82 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"13218\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGD82\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        DIVIDE(-(AG42 - DIM509) * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218]),",
              "        DIVIDE(-AGD82 * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Tap",
            "expression": [
              "",
              "",
              ""
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Netto Avdrag",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG5 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "        CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR GammelResultat = ",
              "    DIVIDE((AG13 - (AG5 + [Grunntall - AG29 - 12328/13218]) - AG6) * 100, [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "",
              "VAR NyResultat = ",
              "    DIVIDE(-(AG5 -[Grunntall - AG28 - 12328/13218] - [Grunntall - AG29 - 12328/13218] ",
              "            - [Grunntall - AG30 - 12328/13218] - [Grunntall - AG31 - 12328/13218] ",
              "            - [Grunntall - AG32 - 12328/13218] - [Grunntall - AG33 - 12328/13218]) * 100, ",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218] ",
              "            - [Grunntall - Differansen mellom FKF/KFenes kjøp og salg til egne FKF/KF - AG23 - 12328/13218] ",
              "            - [Grunntall - Differansen mellom IKSenes kjøp og salg til IKS - AG24 - 12328/13218] ",
              "            - [Grunntall - Differansen FKF/KFenes overføringer og overføringer til FKF/KF - AG25 - 12328/13218] ",
              "            - [Grunntall - Differansen IKSenes overføringer og overføringer fra IKS - AG26 - 12328/13218])",
              "",
              "VAR Resultat = ",
              "    IF(ValgtAar < 2020,",
              "        GammelResultat,",
              "        NyResultat",
              "    )",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Finansinntekter og finansutgifter - Netto finans",
            "expression": [
              "",
              "",
              "VAR ValgtAar = VALUE(SELECTEDVALUE('År'[År]))",
              "",
              "VAR AG5 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] IN {\"12328\", \"13218\"}),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG6 =",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG6\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR AG13 = ",
              "        CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12328\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AG13\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = ",
              "    DIVIDE([Grunntall - Resultat eksterne finanstransaksjoner/Netto finansutgifter - AGD22/AGD85 - 12328/13218] * 100, ",
              "            [Grunntall - Sum driftsinntekter (A) - AGD45 - 12328/13218])",
              "",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 1",
              "    )",
              ")"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Grunnskole",
            "expression": [
              "",
              "",
              "VAR FGK8b = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK8b\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK8b * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(",
              "    ROUND(",
              "        Resultat, 2",
              "    )",
              ")"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - VAR",
            "expression": [
              "",
              "",
              "VAR FGK14 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK14\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK14 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Helse/Omsorg",
            "expression": [
              "",
              "",
              "VAR FGK9 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK9\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK9 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Samferdsel",
            "expression": [
              "",
              "",
              "VAR FGK5 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK5\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK5 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Bolig",
            "expression": [
              "",
              "",
              "VAR FGK16 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK16\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK16 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Barnehage",
            "expression": [
              "",
              "",
              "VAR FGK7 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK7\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK7 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Kultur",
            "expression": [
              "",
              "",
              "VAR FGK2 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK2\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK2 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Admin",
            "expression": [
              "",
              "",
              "VAR FGK1b = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK1b\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK1b * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Næring",
            "expression": [
              "",
              "",
              "VAR FGK4 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK4\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Resultat = DIVIDE(FGK4 * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          },
          {
            "name": "Brutto investeringsutgifter - Annet",
            "expression": [
              "",
              "",
              "VAR DIM190 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"190\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM285 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"285\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR DIM290 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"290\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK12 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK12\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK15 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK15\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK17 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK17\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK1c = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK1c\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR FGK3 = ",
              "    CALCULATE(SUM('Alle Data'[Verdi]),",
              "        FILTER(ALL(Tabeller[Tabellnummer]), [Tabellnummer] = \"12362\"),",
              "        FILTER(ALL(Art[Original dimensjonskode]), [Original dimensjonskode] = \"AGI5\"),",
              "        FILTER(ALL(Funksjon[Original dimensjonskode]), [Original dimensjonskode] = \"FGK3\"),",
              "        FILTER(ALL(Variabel[Variabelnavn]), [Variabelnavn] = \"Beløp (1000 kr)\")",
              "    )",
              "",
              "VAR Korr = 106808",
              "",
              "VAR DimResultat = DIM190 + DIM285 + DIM290 + FGK12 + FGK15 + FGK17 + FGK1c + FGK3 + Korr",
              "",
              "VAR Resultat = DIVIDE(DimResultat * 100, [Grunntall - Brutto investeringsutgifter i alt, konsern - AGI1 - 12364])",
              "",
              "RETURN(ROUND(Resultat, 2))"
            ]
          }
        ]
      },
      {
        "name": "År",
        "columns": [
          {
            "name": "År",
            "dataType": "string",
            "sourceColumn": "År"
          },
          {
            "name": "Årstall",
            "dataType": "string",
            "sourceColumn": "Årstall"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/vk-sxd0e-002;Reporting_KOMOK\",",
                "    dbo_År = Source{[Schema=\"dbo\",Item=\"År\"]}[Data]",
                "in",
                "    dbo_År"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "4b50dd00-2bc4-4226-adcc-afaa2264d904",
        "fromTable": "Alle Data",
        "fromColumn": "Artkode",
        "toTable": "Art",
        "toColumn": "Artkode"
      },
      {
        "name": "ae3dd9e0-6391-4873-814f-f546be9d43af",
        "fromTable": "Alle Data",
        "fromColumn": "Kode",
        "toTable": "Region",
        "toColumn": "Kode"
      },
      {
        "name": "a6a9ef68-bc24-4753-97f0-be9763912084",
        "fromTable": "Alle Data",
        "fromColumn": "Regnskapsbegrepkode",
        "toTable": "Regnskapsbegrep",
        "toColumn": "Regnskapsbegrepkode"
      },
      {
        "name": "d4c5cb7e-0dac-44d5-a7c7-dedcbeec0f20",
        "fromTable": "Alle Data",
        "fromColumn": "Tabell",
        "toTable": "Tabeller",
        "toColumn": "Tabellnummer"
      },
      {
        "name": "39c4585f-88df-4c90-ba29-7001f983e9ba",
        "fromTable": "Alle Data",
        "fromColumn": "Variabel",
        "toTable": "Variabel",
        "toColumn": "Variabelkode"
      },
      {
        "name": "bd66c095-a64b-4453-952a-4fe6eb88af22",
        "fromTable": "Alle Data",
        "fromColumn": "Balansedatakode",
        "toTable": "Balansedata",
        "toColumn": "Balansedatakode"
      },
      {
        "name": "06c4c976-b83f-42c4-90bf-3bd377e09189",
        "fromTable": "Alle Data",
        "fromColumn": "Funksjonkode",
        "toTable": "Funksjon",
        "toColumn": "Funksjonkode"
      },
      {
        "name": "174104c3-8d7d-42f6-91f0-91c9e1a69e8a",
        "fromTable": "Alle Data",
        "fromColumn": "År",
        "toTable": "År",
        "toColumn": "År"
      }
    ],
    "roles": [
      {
        "name": "Brukere",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "I04\\VK.DB.VK-SXD0E-002_KOMOK.DBO",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1078585"
          }
        ]
      },
      {
        "name": "PowerBI",
        "modelPermission": "administrator",
        "members": [
          {
            "memberName": "I04\\vk-PowerBIService",
            "memberId": "S-1-5-21-2036031588-730629661-1306914269-1042837"
          }
        ]
      },
      {
        "name": "API",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "NT AUTHORITY\\IUSR",
            "memberId": "S-1-5-17"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}